/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.api;

import com.google.gson.reflect.TypeToken;
import org.junit.BeforeClass;
import sunbox.sdp.ambari.client.JSON;
import sunbox.sdp.ambari.client.model.*;
import org.junit.Test;
import org.junit.Ignore;
import sunbox.sdp.ambari.client.model.createclusterprocess.*;


import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClustersApi
 */
@Ignore
public class ClustersApiTest extends BaseTest{

    private static ClustersApi api = new ClustersApi();

    @BeforeClass
    public static void init() {
        initClass();
        api = new ClustersApi();
    }
    /**
     * Creates a cluster
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createClusterTest() throws Exception {
        String clusterName = "singlenodeCluster2";
        ClusterRequestSwagger body = readClusterRequestSwaggerFromFile();
        CreateClusterResponseWrapper response = api.createCluster(clusterName, body);
        JSON json = new JSON();
        System.out.println(json.getGson().toJson(response));
    }

    private ClusterRequestSwagger readClusterRequestSwaggerFromFile() {
        byte[] file = new byte[0];
        try {
            file = Files.readAllBytes(Paths.get("/data/home/wangda/work/01-doc/01-尚博信/08-SDP/05-项目资料/blueprint/clustertemplate1.json"));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        String content = new String(file);
        JSON json = new JSON();
        ClusterRequestSwagger obj = json.deserialize(content, new TypeToken<ClusterRequestSwagger>() {
        }.getType());
        return obj;
    }
    
    /**
     * Creates a cluster artifact
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createClusterArtifactTest() throws Exception {
        String clusterName = null;
        String artifactName = null;
        ClusterArtifactRequest body = null;
        api.createClusterArtifact(clusterName, artifactName, body);

        // TODO: test validations
    }
    
    /**
     * Deletes a cluster
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteClusterTest() throws Exception {
        String clusterName = null;
        api.deleteCluster(clusterName);

        // TODO: test validations
    }
    
    /**
     * Deletes a single artifact
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteClusterArtifactTest() throws Exception {
        String clusterName = null;
        String artifactName = null;
        api.deleteClusterArtifact(clusterName, artifactName);

        // TODO: test validations
    }
    
    /**
     * Deletes all artifacts of a cluster that match the provided predicate
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteClusterArtifactsTest() throws Exception {
        String clusterName = null;
        api.deleteClusterArtifacts(clusterName);

        // TODO: test validations
    }
    
    /**
     * Returns information about a specific cluster
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getClusterTest() throws Exception {
        String clusterName = null;
        String fields = null;
        ClusterResponseWrapper response = api.getCluster(clusterName, fields);

        // TODO: test validations
    }
    
    /**
     * Get the details of a cluster artifact
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getClusterArtifactTest() throws Exception {
        String clusterName = null;
        String artifactName = null;
        String fields = null;
        String sortBy = null;
        Integer pageSize = null;
        String from = null;
        String to = null;
        ClusterArtifactResponse response = api.getClusterArtifact(clusterName, artifactName, fields, sortBy, pageSize, from, to);

        // TODO: test validations
    }

    @Test
    public void getClusterCreateProcessTest() throws Exception {
        String clusterName = "singlenodeCluster";
        Long requestId = 12L;
        CreateClusterProcess resp = api.getClusterCreateProcess(clusterName, requestId);
        System.out.println(resp);
    }

    @Test
    public void getClusterCreateProcessTaskTest() throws Exception {
        String clusterName = "singlenodeCluster";
        Long requestId = 12L;
        Long taskId = 10000L;
        CreateClusterProcessTaskDetailWrapper resp = api.getClusterCreateProcessTask(clusterName, requestId, taskId);
        System.out.println(resp);
    }

    @Test
    public void getClusterCreateProcessStageTest() throws Exception {
        String clusterName = "singlenodeCluster";
        Integer requestId = 12;
        Integer stageId = 1;
        CreateClusterProcess resp = api.getClusterCreateProcessStage(clusterName, requestId, stageId);
        System.out.println(resp);
    }


    /**
     * Returns all artifacts associated with the cluster
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getClusterArtifactsTest() throws Exception {
        String clusterName = null;
        String fields = null;
        String sortBy = null;
        Integer pageSize = null;
        Integer from = null;
        Integer to = null;
        List<ClusterArtifactResponse> response = api.getClusterArtifacts(clusterName, fields, sortBy, pageSize, from, to);

        // TODO: test validations
    }
    
    /**
     * Returns all clusters
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getClustersTest() throws Exception {
        String fields = "Clusters/*";
        String sortBy = null;
        Integer pageSize = null;
        Integer from = null;
        Integer to = null;
        List<ClusterResponseWrapper> response = api.getClusters(fields, sortBy, pageSize, from, to);

        // TODO: test validations
    }
    
    /**
     * Updates a cluster
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateClusterTest() throws Exception {
        String clusterName = null;
        ClusterRequestSwagger body = null;
        api.updateCluster(clusterName, body);

        // TODO: test validations
    }
    
    /**
     * Updates a single artifact
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateClusterArtifactTest() throws Exception {
        String clusterName = null;
        String artifactName = null;
        ClusterArtifactRequest body = null;
        api.updateClusterArtifact(clusterName, artifactName, body);

        // TODO: test validations
    }
    
    /**
     * Updates multiple artifacts
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateClusterArtifactsTest() throws Exception {
        String clusterName = null;
        ClusterArtifactRequest body = null;
        api.updateClusterArtifacts(clusterName, body);

        // TODO: test validations
    }
    
}
