/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.api;

import sunbox.sdp.ambari.client.model.HostRequest;
import sunbox.sdp.ambari.client.model.HostResponseWrapper;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HostsApi
 */
@Ignore
public class HostsApiTest {

    private final HostsApi api = new HostsApi();

    
    /**
     * Creates a host
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createHostTest() throws Exception {
        String hostName = null;
        HostRequest body = null;
        api.createHost(hostName, body);

        // TODO: test validations
    }
    
    /**
     * Creates multiple hosts in a single request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createHostsTest() throws Exception {
        HostRequest body = null;
        api.createHosts(body);

        // TODO: test validations
    }
    
    /**
     * Deletes a host
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteHostTest() throws Exception {
        String hostName = null;
        api.deleteHost(hostName);

        // TODO: test validations
    }
    
    /**
     * Deletes multiple hosts in a single request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteHostsTest() throws Exception {
        HostRequest body = null;
        api.deleteHosts(body);

        // TODO: test validations
    }
    
    /**
     * Returns information about a single host
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getHostTest() throws Exception {
        String hostName = null;
        String fields = null;
        HostResponseWrapper response = api.getHost(hostName, fields);

        // TODO: test validations
    }
    
    /**
     * Returns a collection of all hosts
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getHostsTest() throws Exception {
        String fields = null;
        String sortBy = null;
        Integer pageSize = null;
        Integer from = null;
        Integer to = null;
        List<HostResponseWrapper> response = api.getHosts(fields, sortBy, pageSize, from, to);

        // TODO: test validations
    }
    
    /**
     * Updates a host
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateHostTest() throws Exception {
        String hostName = null;
        HostRequest body = null;
        api.updateHost(hostName, body);

        // TODO: test validations
    }
    
    /**
     * Updates multiple hosts in a single request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateHostsTest() throws Exception {
        HostRequest body = null;
        api.updateHosts(body);

        // TODO: test validations
    }
    
}
