/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.api;

import sunbox.sdp.ambari.client.model.SettingRequestSwagger;
import sunbox.sdp.ambari.client.model.SettingResponseWrapper;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SettingsApi
 */
@Ignore
public class SettingsApiTest {

    private final SettingsApi api = new SettingsApi();

    
    /**
     * Creates a setting
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createSettingTest() throws Exception {
        SettingRequestSwagger body = null;
        api.createSetting(body);

        // TODO: test validations
    }
    
    /**
     * Deletes a setting
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteSettingTest() throws Exception {
        String settingName = null;
        api.deleteSetting(settingName);

        // TODO: test validations
    }
    
    /**
     * Returns a specific setting
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSettingTest() throws Exception {
        String settingName = null;
        String fields = null;
        String sortBy = null;
        Integer pageSize = null;
        Integer from = null;
        Integer to = null;
        SettingResponseWrapper response = api.getSetting(settingName, fields, sortBy, pageSize, from, to);

        // TODO: test validations
    }
    
    /**
     * Returns all settings
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSettingsTest() throws Exception {
        String fields = null;
        String sortBy = null;
        Integer pageSize = null;
        Integer from = null;
        Integer to = null;
        List<SettingResponseWrapper> response = api.getSettings(fields, sortBy, pageSize, from, to);

        // TODO: test validations
    }
    
    /**
     * Updates a setting
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateSettingTest() throws Exception {
        String settingName = null;
        SettingRequestSwagger body = null;
        api.updateSetting(settingName, body);

        // TODO: test validations
    }
    
}
