kind: Service
apiVersion: v1
metadata:
  name: rm-api
  namespace: resource-manager
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: rm-api
  type: LoadBalancer