CREATE TABLE if not exists info_vm_statement_item (
    `id` BIGINT NOT NULL AUTO_INCREMENT  COMMENT '自增主键' ,
    `statement_id` VARCHAR(64)    COMMENT '对账单编号' ,
    `vm_name` VARCHAR(100)    COMMENT 'vm name' ,
    `vm_state` VARCHAR(32)    COMMENT 'vm state' ,
    `nic_id` VARCHAR(100)    COMMENT 'nic id' ,
    `nic_state` VARCHAR(32)    COMMENT 'nic state' ,
    `private_ip` VARCHAR(100)    COMMENT 'private ip' ,
    `cluster_id` VARCHAR(100)    COMMENT '集群ID' ,
    `cluster_name` VARCHAR(100)    COMMENT '集群名' ,
    `vm_role` VARCHAR(100)    COMMENT '主机角色' ,
    `group_name` VARCHAR(100)    COMMENT '实例组名' ,
    `host_name` VARCHAR(100)    COMMENT '主机名' ,
    `purchase_type` VARCHAR(32)    COMMENT 'purchase type' ,
    `sku` VARCHAR(32)    COMMENT 'sku' ,
    `cpu` INT   COMMENT 'cpu' ,
    `memory` INT    COMMENT 'memory' ,
    `zone_name` VARCHAR(100)    COMMENT '可用区' ,
    `subnet` VARCHAR(200)    COMMENT '子网' ,
    `physical_zone` VARCHAR(32)    COMMENT 'physical zone' ,
    `vm_tags` VARCHAR(1000)    COMMENT 'vm tags' ,
    `vm_source` VARCHAR(64)    COMMENT '来源AZURE SDP YARN' ,
    `vm_created_time` DATETIME    COMMENT 'vm实际创建时间' ,
    `created_time` DATETIME    COMMENT '创建时间' ,
    `modified_time` DATETIME    COMMENT '修改时间',
    PRIMARY KEY (id)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT = '对账单主体明细(ODS)';