/*
 * This file is generated by jOOQ.
 */
package com.azure.csu.tiger.ansible.agent.jooq.tables.records;


import com.azure.csu.tiger.ansible.agent.jooq.tables.Jobresults;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobresultsRecord extends UpdatableRecordImpl<JobresultsRecord> implements Record4<Integer, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sdp.jobresults.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sdp.jobresults.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sdp.jobresults.JobID</code>.
     */
    public void setJobid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sdp.jobresults.JobID</code>.
     */
    public String getJobid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sdp.jobresults.AnsibleLog</code>.
     */
    public void setAnsiblelog(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sdp.jobresults.AnsibleLog</code>.
     */
    public String getAnsiblelog() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sdp.jobresults.CreateTime</code>.
     */
    public void setCreatetime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>sdp.jobresults.CreateTime</code>.
     */
    public LocalDateTime getCreatetime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Jobresults.JOBRESULTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Jobresults.JOBRESULTS.JOBID;
    }

    @Override
    public Field<String> field3() {
        return Jobresults.JOBRESULTS.ANSIBLELOG;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Jobresults.JOBRESULTS.CREATETIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getJobid();
    }

    @Override
    public String component3() {
        return getAnsiblelog();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatetime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getJobid();
    }

    @Override
    public String value3() {
        return getAnsiblelog();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatetime();
    }

    @Override
    public JobresultsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public JobresultsRecord value2(String value) {
        setJobid(value);
        return this;
    }

    @Override
    public JobresultsRecord value3(String value) {
        setAnsiblelog(value);
        return this;
    }

    @Override
    public JobresultsRecord value4(LocalDateTime value) {
        setCreatetime(value);
        return this;
    }

    @Override
    public JobresultsRecord values(Integer value1, String value2, String value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobresultsRecord
     */
    public JobresultsRecord() {
        super(Jobresults.JOBRESULTS);
    }

    /**
     * Create a detached, initialised JobresultsRecord
     */
    public JobresultsRecord(Integer id, String jobid, String ansiblelog, LocalDateTime createtime) {
        super(Jobresults.JOBRESULTS);

        setId(id);
        setJobid(jobid);
        setAnsiblelog(ansiblelog);
        setCreatetime(createtime);
    }
}
