/*
 * This file is generated by jOOQ.
 */
package com.azure.csu.tiger.rm.task.jooq;


import com.azure.csu.tiger.rm.task.jooq.tables.SdpRmJobs;
import com.azure.csu.tiger.rm.task.jooq.tables.records.SdpRmJobsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * sdp.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SdpRmJobsRecord> KEY_SDP_RM_JOBS_JOBID_UNIQUE = Internal.createUniqueKey(SdpRmJobs.SDP_RM_JOBS, DSL.name("KEY_sdp_rm_jobs_jobId_UNIQUE"), new TableField[] { SdpRmJobs.SDP_RM_JOBS.JOBID }, true);
    public static final UniqueKey<SdpRmJobsRecord> KEY_SDP_RM_JOBS_PRIMARY = Internal.createUniqueKey(SdpRmJobs.SDP_RM_JOBS, DSL.name("KEY_sdp_rm_jobs_PRIMARY"), new TableField[] { SdpRmJobs.SDP_RM_JOBS.ID }, true);
}
