/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import sunbox.sdp.ambari.client.model.WidgetResponse;

/**
 * ActiveWidgetLayoutResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class ActiveWidgetLayoutResponse {
  @SerializedName("WidgetLayoutInfo/cluster_name")
  private String widgetLayoutInfoclusterName = null;

  @SerializedName("WidgetLayoutInfo/display_name")
  private String widgetLayoutInfodisplayName = null;

  @SerializedName("WidgetLayoutInfo/layout_name")
  private String widgetLayoutInfolayoutName = null;

  @SerializedName("WidgetLayoutInfo/scope")
  private String widgetLayoutInfoscope = null;

  @SerializedName("WidgetLayoutInfo/section_name")
  private String widgetLayoutInfosectionName = null;

  @SerializedName("WidgetLayoutInfo/user_name")
  private String widgetLayoutInfouserName = null;

  @SerializedName("WidgetLayoutInfo/widgets")
  private List<Map<String, WidgetResponse>> widgetLayoutInfowidgets = null;

  public ActiveWidgetLayoutResponse widgetLayoutInfoclusterName(String widgetLayoutInfoclusterName) {
    this.widgetLayoutInfoclusterName = widgetLayoutInfoclusterName;
    return this;
  }

   /**
   * Get widgetLayoutInfoclusterName
   * @return widgetLayoutInfoclusterName
  **/
  @ApiModelProperty(value = "")
  public String getWidgetLayoutInfoclusterName() {
    return widgetLayoutInfoclusterName;
  }

  public void setWidgetLayoutInfoclusterName(String widgetLayoutInfoclusterName) {
    this.widgetLayoutInfoclusterName = widgetLayoutInfoclusterName;
  }

  public ActiveWidgetLayoutResponse widgetLayoutInfodisplayName(String widgetLayoutInfodisplayName) {
    this.widgetLayoutInfodisplayName = widgetLayoutInfodisplayName;
    return this;
  }

   /**
   * Get widgetLayoutInfodisplayName
   * @return widgetLayoutInfodisplayName
  **/
  @ApiModelProperty(value = "")
  public String getWidgetLayoutInfodisplayName() {
    return widgetLayoutInfodisplayName;
  }

  public void setWidgetLayoutInfodisplayName(String widgetLayoutInfodisplayName) {
    this.widgetLayoutInfodisplayName = widgetLayoutInfodisplayName;
  }

  public ActiveWidgetLayoutResponse widgetLayoutInfolayoutName(String widgetLayoutInfolayoutName) {
    this.widgetLayoutInfolayoutName = widgetLayoutInfolayoutName;
    return this;
  }

   /**
   * Get widgetLayoutInfolayoutName
   * @return widgetLayoutInfolayoutName
  **/
  @ApiModelProperty(value = "")
  public String getWidgetLayoutInfolayoutName() {
    return widgetLayoutInfolayoutName;
  }

  public void setWidgetLayoutInfolayoutName(String widgetLayoutInfolayoutName) {
    this.widgetLayoutInfolayoutName = widgetLayoutInfolayoutName;
  }

  public ActiveWidgetLayoutResponse widgetLayoutInfoscope(String widgetLayoutInfoscope) {
    this.widgetLayoutInfoscope = widgetLayoutInfoscope;
    return this;
  }

   /**
   * Get widgetLayoutInfoscope
   * @return widgetLayoutInfoscope
  **/
  @ApiModelProperty(value = "")
  public String getWidgetLayoutInfoscope() {
    return widgetLayoutInfoscope;
  }

  public void setWidgetLayoutInfoscope(String widgetLayoutInfoscope) {
    this.widgetLayoutInfoscope = widgetLayoutInfoscope;
  }

  public ActiveWidgetLayoutResponse widgetLayoutInfosectionName(String widgetLayoutInfosectionName) {
    this.widgetLayoutInfosectionName = widgetLayoutInfosectionName;
    return this;
  }

   /**
   * Get widgetLayoutInfosectionName
   * @return widgetLayoutInfosectionName
  **/
  @ApiModelProperty(value = "")
  public String getWidgetLayoutInfosectionName() {
    return widgetLayoutInfosectionName;
  }

  public void setWidgetLayoutInfosectionName(String widgetLayoutInfosectionName) {
    this.widgetLayoutInfosectionName = widgetLayoutInfosectionName;
  }

  public ActiveWidgetLayoutResponse widgetLayoutInfouserName(String widgetLayoutInfouserName) {
    this.widgetLayoutInfouserName = widgetLayoutInfouserName;
    return this;
  }

   /**
   * Get widgetLayoutInfouserName
   * @return widgetLayoutInfouserName
  **/
  @ApiModelProperty(value = "")
  public String getWidgetLayoutInfouserName() {
    return widgetLayoutInfouserName;
  }

  public void setWidgetLayoutInfouserName(String widgetLayoutInfouserName) {
    this.widgetLayoutInfouserName = widgetLayoutInfouserName;
  }

  public ActiveWidgetLayoutResponse widgetLayoutInfowidgets(List<Map<String, WidgetResponse>> widgetLayoutInfowidgets) {
    this.widgetLayoutInfowidgets = widgetLayoutInfowidgets;
    return this;
  }

  public ActiveWidgetLayoutResponse addWidgetLayoutInfowidgetsItem(Map<String, WidgetResponse> widgetLayoutInfowidgetsItem) {
    if (this.widgetLayoutInfowidgets == null) {
      this.widgetLayoutInfowidgets = new ArrayList<Map<String, WidgetResponse>>();
    }
    this.widgetLayoutInfowidgets.add(widgetLayoutInfowidgetsItem);
    return this;
  }

   /**
   * Get widgetLayoutInfowidgets
   * @return widgetLayoutInfowidgets
  **/
  @ApiModelProperty(value = "")
  public List<Map<String, WidgetResponse>> getWidgetLayoutInfowidgets() {
    return widgetLayoutInfowidgets;
  }

  public void setWidgetLayoutInfowidgets(List<Map<String, WidgetResponse>> widgetLayoutInfowidgets) {
    this.widgetLayoutInfowidgets = widgetLayoutInfowidgets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActiveWidgetLayoutResponse activeWidgetLayoutResponse = (ActiveWidgetLayoutResponse) o;
    return Objects.equals(this.widgetLayoutInfoclusterName, activeWidgetLayoutResponse.widgetLayoutInfoclusterName) &&
        Objects.equals(this.widgetLayoutInfodisplayName, activeWidgetLayoutResponse.widgetLayoutInfodisplayName) &&
        Objects.equals(this.widgetLayoutInfolayoutName, activeWidgetLayoutResponse.widgetLayoutInfolayoutName) &&
        Objects.equals(this.widgetLayoutInfoscope, activeWidgetLayoutResponse.widgetLayoutInfoscope) &&
        Objects.equals(this.widgetLayoutInfosectionName, activeWidgetLayoutResponse.widgetLayoutInfosectionName) &&
        Objects.equals(this.widgetLayoutInfouserName, activeWidgetLayoutResponse.widgetLayoutInfouserName) &&
        Objects.equals(this.widgetLayoutInfowidgets, activeWidgetLayoutResponse.widgetLayoutInfowidgets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(widgetLayoutInfoclusterName, widgetLayoutInfodisplayName, widgetLayoutInfolayoutName, widgetLayoutInfoscope, widgetLayoutInfosectionName, widgetLayoutInfouserName, widgetLayoutInfowidgets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActiveWidgetLayoutResponse {\n");
    
    sb.append("    widgetLayoutInfoclusterName: ").append(toIndentedString(widgetLayoutInfoclusterName)).append("\n");
    sb.append("    widgetLayoutInfodisplayName: ").append(toIndentedString(widgetLayoutInfodisplayName)).append("\n");
    sb.append("    widgetLayoutInfolayoutName: ").append(toIndentedString(widgetLayoutInfolayoutName)).append("\n");
    sb.append("    widgetLayoutInfoscope: ").append(toIndentedString(widgetLayoutInfoscope)).append("\n");
    sb.append("    widgetLayoutInfosectionName: ").append(toIndentedString(widgetLayoutInfosectionName)).append("\n");
    sb.append("    widgetLayoutInfouserName: ").append(toIndentedString(widgetLayoutInfouserName)).append("\n");
    sb.append("    widgetLayoutInfowidgets: ").append(toIndentedString(widgetLayoutInfowidgets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

