/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import sunbox.sdp.ambari.client.model.Alternative;
import sunbox.sdp.ambari.client.model.Directory;
import sunbox.sdp.ambari.client.model.ExistingUser;
import sunbox.sdp.ambari.client.model.HostHealth;
import sunbox.sdp.ambari.client.model.PackageDetail;

/**
 * AgentEnv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class AgentEnv {
  @SerializedName("stackFoldersAndFiles")
  private List<Directory> stackFoldersAndFiles = null;

  @SerializedName("alternatives")
  private List<Alternative> alternatives = null;

  @SerializedName("existingUsers")
  private List<ExistingUser> existingUsers = null;

  @SerializedName("existingRepos")
  private List<String> existingRepos = null;

  @SerializedName("installedPackages")
  private List<PackageDetail> installedPackages = null;

  @SerializedName("hostHealth")
  private HostHealth hostHealth = null;

  @SerializedName("umask")
  private Integer umask = null;

  @SerializedName("transparentHugePage")
  private String transparentHugePage = null;

  @SerializedName("firewallRunning")
  private Boolean firewallRunning = false;

  @SerializedName("firewallName")
  private String firewallName = null;

  @SerializedName("hasUnlimitedJcePolicy")
  private Boolean hasUnlimitedJcePolicy = false;

  @SerializedName("reverseLookup")
  private Boolean reverseLookup = false;

  public AgentEnv stackFoldersAndFiles(List<Directory> stackFoldersAndFiles) {
    this.stackFoldersAndFiles = stackFoldersAndFiles;
    return this;
  }

  public AgentEnv addStackFoldersAndFilesItem(Directory stackFoldersAndFilesItem) {
    if (this.stackFoldersAndFiles == null) {
      this.stackFoldersAndFiles = new ArrayList<Directory>();
    }
    this.stackFoldersAndFiles.add(stackFoldersAndFilesItem);
    return this;
  }

   /**
   * Get stackFoldersAndFiles
   * @return stackFoldersAndFiles
  **/
  @ApiModelProperty(value = "")
  public List<Directory> getStackFoldersAndFiles() {
    return stackFoldersAndFiles;
  }

  public void setStackFoldersAndFiles(List<Directory> stackFoldersAndFiles) {
    this.stackFoldersAndFiles = stackFoldersAndFiles;
  }

  public AgentEnv alternatives(List<Alternative> alternatives) {
    this.alternatives = alternatives;
    return this;
  }

  public AgentEnv addAlternativesItem(Alternative alternativesItem) {
    if (this.alternatives == null) {
      this.alternatives = new ArrayList<Alternative>();
    }
    this.alternatives.add(alternativesItem);
    return this;
  }

   /**
   * Get alternatives
   * @return alternatives
  **/
  @ApiModelProperty(value = "")
  public List<Alternative> getAlternatives() {
    return alternatives;
  }

  public void setAlternatives(List<Alternative> alternatives) {
    this.alternatives = alternatives;
  }

  public AgentEnv existingUsers(List<ExistingUser> existingUsers) {
    this.existingUsers = existingUsers;
    return this;
  }

  public AgentEnv addExistingUsersItem(ExistingUser existingUsersItem) {
    if (this.existingUsers == null) {
      this.existingUsers = new ArrayList<ExistingUser>();
    }
    this.existingUsers.add(existingUsersItem);
    return this;
  }

   /**
   * Get existingUsers
   * @return existingUsers
  **/
  @ApiModelProperty(value = "")
  public List<ExistingUser> getExistingUsers() {
    return existingUsers;
  }

  public void setExistingUsers(List<ExistingUser> existingUsers) {
    this.existingUsers = existingUsers;
  }

  public AgentEnv existingRepos(List<String> existingRepos) {
    this.existingRepos = existingRepos;
    return this;
  }

  public AgentEnv addExistingReposItem(String existingReposItem) {
    if (this.existingRepos == null) {
      this.existingRepos = new ArrayList<String>();
    }
    this.existingRepos.add(existingReposItem);
    return this;
  }

   /**
   * Get existingRepos
   * @return existingRepos
  **/
  @ApiModelProperty(value = "")
  public List<String> getExistingRepos() {
    return existingRepos;
  }

  public void setExistingRepos(List<String> existingRepos) {
    this.existingRepos = existingRepos;
  }

  public AgentEnv installedPackages(List<PackageDetail> installedPackages) {
    this.installedPackages = installedPackages;
    return this;
  }

  public AgentEnv addInstalledPackagesItem(PackageDetail installedPackagesItem) {
    if (this.installedPackages == null) {
      this.installedPackages = new ArrayList<PackageDetail>();
    }
    this.installedPackages.add(installedPackagesItem);
    return this;
  }

   /**
   * Get installedPackages
   * @return installedPackages
  **/
  @ApiModelProperty(value = "")
  public List<PackageDetail> getInstalledPackages() {
    return installedPackages;
  }

  public void setInstalledPackages(List<PackageDetail> installedPackages) {
    this.installedPackages = installedPackages;
  }

  public AgentEnv hostHealth(HostHealth hostHealth) {
    this.hostHealth = hostHealth;
    return this;
  }

   /**
   * Get hostHealth
   * @return hostHealth
  **/
  @ApiModelProperty(value = "")
  public HostHealth getHostHealth() {
    return hostHealth;
  }

  public void setHostHealth(HostHealth hostHealth) {
    this.hostHealth = hostHealth;
  }

  public AgentEnv umask(Integer umask) {
    this.umask = umask;
    return this;
  }

   /**
   * Get umask
   * @return umask
  **/
  @ApiModelProperty(value = "")
  public Integer getUmask() {
    return umask;
  }

  public void setUmask(Integer umask) {
    this.umask = umask;
  }

  public AgentEnv transparentHugePage(String transparentHugePage) {
    this.transparentHugePage = transparentHugePage;
    return this;
  }

   /**
   * Get transparentHugePage
   * @return transparentHugePage
  **/
  @ApiModelProperty(value = "")
  public String getTransparentHugePage() {
    return transparentHugePage;
  }

  public void setTransparentHugePage(String transparentHugePage) {
    this.transparentHugePage = transparentHugePage;
  }

  public AgentEnv firewallRunning(Boolean firewallRunning) {
    this.firewallRunning = firewallRunning;
    return this;
  }

   /**
   * Get firewallRunning
   * @return firewallRunning
  **/
  @ApiModelProperty(value = "")
  public Boolean isFirewallRunning() {
    return firewallRunning;
  }

  public void setFirewallRunning(Boolean firewallRunning) {
    this.firewallRunning = firewallRunning;
  }

  public AgentEnv firewallName(String firewallName) {
    this.firewallName = firewallName;
    return this;
  }

   /**
   * Get firewallName
   * @return firewallName
  **/
  @ApiModelProperty(value = "")
  public String getFirewallName() {
    return firewallName;
  }

  public void setFirewallName(String firewallName) {
    this.firewallName = firewallName;
  }

  public AgentEnv hasUnlimitedJcePolicy(Boolean hasUnlimitedJcePolicy) {
    this.hasUnlimitedJcePolicy = hasUnlimitedJcePolicy;
    return this;
  }

   /**
   * Get hasUnlimitedJcePolicy
   * @return hasUnlimitedJcePolicy
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasUnlimitedJcePolicy() {
    return hasUnlimitedJcePolicy;
  }

  public void setHasUnlimitedJcePolicy(Boolean hasUnlimitedJcePolicy) {
    this.hasUnlimitedJcePolicy = hasUnlimitedJcePolicy;
  }

  public AgentEnv reverseLookup(Boolean reverseLookup) {
    this.reverseLookup = reverseLookup;
    return this;
  }

   /**
   * Get reverseLookup
   * @return reverseLookup
  **/
  @ApiModelProperty(value = "")
  public Boolean isReverseLookup() {
    return reverseLookup;
  }

  public void setReverseLookup(Boolean reverseLookup) {
    this.reverseLookup = reverseLookup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgentEnv agentEnv = (AgentEnv) o;
    return Objects.equals(this.stackFoldersAndFiles, agentEnv.stackFoldersAndFiles) &&
        Objects.equals(this.alternatives, agentEnv.alternatives) &&
        Objects.equals(this.existingUsers, agentEnv.existingUsers) &&
        Objects.equals(this.existingRepos, agentEnv.existingRepos) &&
        Objects.equals(this.installedPackages, agentEnv.installedPackages) &&
        Objects.equals(this.hostHealth, agentEnv.hostHealth) &&
        Objects.equals(this.umask, agentEnv.umask) &&
        Objects.equals(this.transparentHugePage, agentEnv.transparentHugePage) &&
        Objects.equals(this.firewallRunning, agentEnv.firewallRunning) &&
        Objects.equals(this.firewallName, agentEnv.firewallName) &&
        Objects.equals(this.hasUnlimitedJcePolicy, agentEnv.hasUnlimitedJcePolicy) &&
        Objects.equals(this.reverseLookup, agentEnv.reverseLookup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stackFoldersAndFiles, alternatives, existingUsers, existingRepos, installedPackages, hostHealth, umask, transparentHugePage, firewallRunning, firewallName, hasUnlimitedJcePolicy, reverseLookup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentEnv {\n");
    
    sb.append("    stackFoldersAndFiles: ").append(toIndentedString(stackFoldersAndFiles)).append("\n");
    sb.append("    alternatives: ").append(toIndentedString(alternatives)).append("\n");
    sb.append("    existingUsers: ").append(toIndentedString(existingUsers)).append("\n");
    sb.append("    existingRepos: ").append(toIndentedString(existingRepos)).append("\n");
    sb.append("    installedPackages: ").append(toIndentedString(installedPackages)).append("\n");
    sb.append("    hostHealth: ").append(toIndentedString(hostHealth)).append("\n");
    sb.append("    umask: ").append(toIndentedString(umask)).append("\n");
    sb.append("    transparentHugePage: ").append(toIndentedString(transparentHugePage)).append("\n");
    sb.append("    firewallRunning: ").append(toIndentedString(firewallRunning)).append("\n");
    sb.append("    firewallName: ").append(toIndentedString(firewallName)).append("\n");
    sb.append("    hasUnlimitedJcePolicy: ").append(toIndentedString(hasUnlimitedJcePolicy)).append("\n");
    sb.append("    reverseLookup: ").append(toIndentedString(reverseLookup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

