/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import sunbox.sdp.ambari.client.model.RequestBodyInfo;

/**
 * BatchRequestRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class BatchRequestRequest {
  @SerializedName("type")
  private String type = null;

  @SerializedName("uri")
  private String uri = null;

  @SerializedName("order_id")
  private Long orderId = null;

  @SerializedName("RequestBodyInfo")
  private RequestBodyInfo requestBodyInfo = null;

  public BatchRequestRequest type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public BatchRequestRequest uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @ApiModelProperty(value = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public BatchRequestRequest orderId(Long orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @ApiModelProperty(value = "")
  public Long getOrderId() {
    return orderId;
  }

  public void setOrderId(Long orderId) {
    this.orderId = orderId;
  }

  public BatchRequestRequest requestBodyInfo(RequestBodyInfo requestBodyInfo) {
    this.requestBodyInfo = requestBodyInfo;
    return this;
  }

   /**
   * Get requestBodyInfo
   * @return requestBodyInfo
  **/
  @ApiModelProperty(value = "")
  public RequestBodyInfo getRequestBodyInfo() {
    return requestBodyInfo;
  }

  public void setRequestBodyInfo(RequestBodyInfo requestBodyInfo) {
    this.requestBodyInfo = requestBodyInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchRequestRequest batchRequestRequest = (BatchRequestRequest) o;
    return Objects.equals(this.type, batchRequestRequest.type) &&
        Objects.equals(this.uri, batchRequestRequest.uri) &&
        Objects.equals(this.orderId, batchRequestRequest.orderId) &&
        Objects.equals(this.requestBodyInfo, batchRequestRequest.requestBodyInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, uri, orderId, requestBodyInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchRequestRequest {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    requestBodyInfo: ").append(toIndentedString(requestBodyInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

