/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BatchSettings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class BatchSettings {
  @SerializedName("batch_separation_in_seconds")
  private Integer batchSeparationInSeconds = null;

  @SerializedName("task_failure_tolerance_limit")
  private Integer taskFailureToleranceLimit = null;

  public BatchSettings batchSeparationInSeconds(Integer batchSeparationInSeconds) {
    this.batchSeparationInSeconds = batchSeparationInSeconds;
    return this;
  }

   /**
   * Get batchSeparationInSeconds
   * @return batchSeparationInSeconds
  **/
  @ApiModelProperty(value = "")
  public Integer getBatchSeparationInSeconds() {
    return batchSeparationInSeconds;
  }

  public void setBatchSeparationInSeconds(Integer batchSeparationInSeconds) {
    this.batchSeparationInSeconds = batchSeparationInSeconds;
  }

  public BatchSettings taskFailureToleranceLimit(Integer taskFailureToleranceLimit) {
    this.taskFailureToleranceLimit = taskFailureToleranceLimit;
    return this;
  }

   /**
   * Get taskFailureToleranceLimit
   * @return taskFailureToleranceLimit
  **/
  @ApiModelProperty(value = "")
  public Integer getTaskFailureToleranceLimit() {
    return taskFailureToleranceLimit;
  }

  public void setTaskFailureToleranceLimit(Integer taskFailureToleranceLimit) {
    this.taskFailureToleranceLimit = taskFailureToleranceLimit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchSettings batchSettings = (BatchSettings) o;
    return Objects.equals(this.batchSeparationInSeconds, batchSettings.batchSeparationInSeconds) &&
        Objects.equals(this.taskFailureToleranceLimit, batchSettings.taskFailureToleranceLimit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batchSeparationInSeconds, taskFailureToleranceLimit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchSettings {\n");
    
    sb.append("    batchSeparationInSeconds: ").append(toIndentedString(batchSeparationInSeconds)).append("\n");
    sb.append("    taskFailureToleranceLimit: ").append(toIndentedString(taskFailureToleranceLimit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

