/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import sunbox.sdp.ambari.client.model.BlueprintInfo;
import sunbox.sdp.ambari.client.model.HostGroupInfo;

/**
 * BlueprintSwagger
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class BlueprintSwagger {

  @SerializedName("href")
  private String href;

  @SerializedName("configurations")
  private List<Map<String, Object>> configurations = null;

  @SerializedName("Blueprints")
  private BlueprintInfo blueprints = null;

  @SerializedName("host_groups")
  private List<HostGroupInfo> hostGroups = null;

  public BlueprintSwagger configurations(List<Map<String, Object>> configurations) {
    this.configurations = configurations;
    return this;
  }

  public BlueprintSwagger addConfigurationsItem(Map<String, Object> configurationsItem) {
    if (this.configurations == null) {
      this.configurations = new ArrayList<Map<String, Object>>();
    }
    this.configurations.add(configurationsItem);
    return this;
  }

   /**
   * Get configurations
   * @return configurations
  **/
  @ApiModelProperty(value = "")
  public List<Map<String, Object>> getConfigurations() {
    return configurations;
  }

  public void setConfigurations(List<Map<String, Object>> configurations) {
    this.configurations = configurations;
  }

  public BlueprintSwagger blueprints(BlueprintInfo blueprints) {
    this.blueprints = blueprints;
    return this;
  }

   /**
   * Get blueprints
   * @return blueprints
  **/
  @ApiModelProperty(value = "")
  public BlueprintInfo getBlueprints() {
    return blueprints;
  }

  public void setBlueprints(BlueprintInfo blueprints) {
    this.blueprints = blueprints;
  }

  public BlueprintSwagger hostGroups(List<HostGroupInfo> hostGroups) {
    this.hostGroups = hostGroups;
    return this;
  }

  public BlueprintSwagger addHostGroupsItem(HostGroupInfo hostGroupsItem) {
    if (this.hostGroups == null) {
      this.hostGroups = new ArrayList<HostGroupInfo>();
    }
    this.hostGroups.add(hostGroupsItem);
    return this;
  }

   /**
   * Get hostGroups
   * @return hostGroups
  **/
  @ApiModelProperty(value = "")
  public List<HostGroupInfo> getHostGroups() {
    return hostGroups;
  }

  public void setHostGroups(List<HostGroupInfo> hostGroups) {
    this.hostGroups = hostGroups;
  }

  @ApiModelProperty(value = "")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlueprintSwagger blueprintSwagger = (BlueprintSwagger) o;
    return Objects.equals(this.configurations, blueprintSwagger.configurations) &&
        Objects.equals(this.blueprints, blueprintSwagger.blueprints) &&
        Objects.equals(this.hostGroups, blueprintSwagger.hostGroups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configurations, blueprints, hostGroups);
  }



  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlueprintSwagger {\n");
    
    sb.append("    configurations: ").append(toIndentedString(configurations)).append("\n");
    sb.append("    blueprints: ").append(toIndentedString(blueprints)).append("\n");
    sb.append("    hostGroups: ").append(toIndentedString(hostGroups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

