/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import sunbox.sdp.ambari.client.model.ClusterServiceArtifactResponseInfo;

/**
 * ClusterServiceArtifactResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class ClusterServiceArtifactResponse {
  @SerializedName("artifact_data")
  private Map<String, Object> artifactData = null;

  @SerializedName("Artifacts")
  private ClusterServiceArtifactResponseInfo artifacts = null;

  public ClusterServiceArtifactResponse artifactData(Map<String, Object> artifactData) {
    this.artifactData = artifactData;
    return this;
  }

  public ClusterServiceArtifactResponse putArtifactDataItem(String key, Object artifactDataItem) {
    if (this.artifactData == null) {
      this.artifactData = new HashMap<String, Object>();
    }
    this.artifactData.put(key, artifactDataItem);
    return this;
  }

   /**
   * Get artifactData
   * @return artifactData
  **/
  @ApiModelProperty(value = "")
  public Map<String, Object> getArtifactData() {
    return artifactData;
  }

  public void setArtifactData(Map<String, Object> artifactData) {
    this.artifactData = artifactData;
  }

  public ClusterServiceArtifactResponse artifacts(ClusterServiceArtifactResponseInfo artifacts) {
    this.artifacts = artifacts;
    return this;
  }

   /**
   * Get artifacts
   * @return artifacts
  **/
  @ApiModelProperty(value = "")
  public ClusterServiceArtifactResponseInfo getArtifacts() {
    return artifacts;
  }

  public void setArtifacts(ClusterServiceArtifactResponseInfo artifacts) {
    this.artifacts = artifacts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterServiceArtifactResponse clusterServiceArtifactResponse = (ClusterServiceArtifactResponse) o;
    return Objects.equals(this.artifactData, clusterServiceArtifactResponse.artifactData) &&
        Objects.equals(this.artifacts, clusterServiceArtifactResponse.artifacts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(artifactData, artifacts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterServiceArtifactResponse {\n");
    
    sb.append("    artifactData: ").append(toIndentedString(artifactData)).append("\n");
    sb.append("    artifacts: ").append(toIndentedString(artifacts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

