/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ComponentRecoveryReport
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class ComponentRecoveryReport {
  @SerializedName("name")
  private String name = null;

  @SerializedName("numAttempts")
  private Integer numAttempts = null;

  @SerializedName("limitReached")
  private Boolean limitReached = false;

  public ComponentRecoveryReport name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ComponentRecoveryReport numAttempts(Integer numAttempts) {
    this.numAttempts = numAttempts;
    return this;
  }

   /**
   * Get numAttempts
   * @return numAttempts
  **/
  @ApiModelProperty(value = "")
  public Integer getNumAttempts() {
    return numAttempts;
  }

  public void setNumAttempts(Integer numAttempts) {
    this.numAttempts = numAttempts;
  }

  public ComponentRecoveryReport limitReached(Boolean limitReached) {
    this.limitReached = limitReached;
    return this;
  }

   /**
   * Get limitReached
   * @return limitReached
  **/
  @ApiModelProperty(value = "")
  public Boolean isLimitReached() {
    return limitReached;
  }

  public void setLimitReached(Boolean limitReached) {
    this.limitReached = limitReached;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComponentRecoveryReport componentRecoveryReport = (ComponentRecoveryReport) o;
    return Objects.equals(this.name, componentRecoveryReport.name) &&
        Objects.equals(this.numAttempts, componentRecoveryReport.numAttempts) &&
        Objects.equals(this.limitReached, componentRecoveryReport.limitReached);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, numAttempts, limitReached);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComponentRecoveryReport {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    numAttempts: ").append(toIndentedString(numAttempts)).append("\n");
    sb.append("    limitReached: ").append(toIndentedString(limitReached)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

