/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import sunbox.sdp.ambari.client.model.ConfigCondition;
import sunbox.sdp.ambari.client.model.ValueAttributesInfo;

/**
 * ConfigPlacement
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class ConfigPlacement {
  @SerializedName("config")
  private String config = null;

  @SerializedName("subsection-name")
  private String subsectionName = null;

  @SerializedName("subsection-tab-name")
  private String subsectionTabName = null;

  @SerializedName("property_value_attributes")
  private ValueAttributesInfo propertyValueAttributes = null;

  @SerializedName("depends-on")
  private List<ConfigCondition> dependsOn = null;

  @SerializedName("removed")
  private Boolean removed = false;

  public ConfigPlacement config(String config) {
    this.config = config;
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  @ApiModelProperty(value = "")
  public String getConfig() {
    return config;
  }

  public void setConfig(String config) {
    this.config = config;
  }

  public ConfigPlacement subsectionName(String subsectionName) {
    this.subsectionName = subsectionName;
    return this;
  }

   /**
   * Get subsectionName
   * @return subsectionName
  **/
  @ApiModelProperty(value = "")
  public String getSubsectionName() {
    return subsectionName;
  }

  public void setSubsectionName(String subsectionName) {
    this.subsectionName = subsectionName;
  }

  public ConfigPlacement subsectionTabName(String subsectionTabName) {
    this.subsectionTabName = subsectionTabName;
    return this;
  }

   /**
   * Get subsectionTabName
   * @return subsectionTabName
  **/
  @ApiModelProperty(value = "")
  public String getSubsectionTabName() {
    return subsectionTabName;
  }

  public void setSubsectionTabName(String subsectionTabName) {
    this.subsectionTabName = subsectionTabName;
  }

  public ConfigPlacement propertyValueAttributes(ValueAttributesInfo propertyValueAttributes) {
    this.propertyValueAttributes = propertyValueAttributes;
    return this;
  }

   /**
   * Get propertyValueAttributes
   * @return propertyValueAttributes
  **/
  @ApiModelProperty(value = "")
  public ValueAttributesInfo getPropertyValueAttributes() {
    return propertyValueAttributes;
  }

  public void setPropertyValueAttributes(ValueAttributesInfo propertyValueAttributes) {
    this.propertyValueAttributes = propertyValueAttributes;
  }

  public ConfigPlacement dependsOn(List<ConfigCondition> dependsOn) {
    this.dependsOn = dependsOn;
    return this;
  }

  public ConfigPlacement addDependsOnItem(ConfigCondition dependsOnItem) {
    if (this.dependsOn == null) {
      this.dependsOn = new ArrayList<ConfigCondition>();
    }
    this.dependsOn.add(dependsOnItem);
    return this;
  }

   /**
   * Get dependsOn
   * @return dependsOn
  **/
  @ApiModelProperty(value = "")
  public List<ConfigCondition> getDependsOn() {
    return dependsOn;
  }

  public void setDependsOn(List<ConfigCondition> dependsOn) {
    this.dependsOn = dependsOn;
  }

  public ConfigPlacement removed(Boolean removed) {
    this.removed = removed;
    return this;
  }

   /**
   * Get removed
   * @return removed
  **/
  @ApiModelProperty(value = "")
  public Boolean isRemoved() {
    return removed;
  }

  public void setRemoved(Boolean removed) {
    this.removed = removed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigPlacement configPlacement = (ConfigPlacement) o;
    return Objects.equals(this.config, configPlacement.config) &&
        Objects.equals(this.subsectionName, configPlacement.subsectionName) &&
        Objects.equals(this.subsectionTabName, configPlacement.subsectionTabName) &&
        Objects.equals(this.propertyValueAttributes, configPlacement.propertyValueAttributes) &&
        Objects.equals(this.dependsOn, configPlacement.dependsOn) &&
        Objects.equals(this.removed, configPlacement.removed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(config, subsectionName, subsectionTabName, propertyValueAttributes, dependsOn, removed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigPlacement {\n");
    
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    subsectionName: ").append(toIndentedString(subsectionName)).append("\n");
    sb.append("    subsectionTabName: ").append(toIndentedString(subsectionTabName)).append("\n");
    sb.append("    propertyValueAttributes: ").append(toIndentedString(propertyValueAttributes)).append("\n");
    sb.append("    dependsOn: ").append(toIndentedString(dependsOn)).append("\n");
    sb.append("    removed: ").append(toIndentedString(removed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

