/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ConfigurationRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class ConfigurationRequest {
  @SerializedName("Config/cluster_name")
  private String configclusterName = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("version")
  private Long version = null;

  @SerializedName("properties")
  private Map<String, String> properties = null;

  @SerializedName("tag")
  private String tag = null;

  @SerializedName("properties_attributes")
  private Map<String, Map<String, String>> propertiesAttributes = null;

  public ConfigurationRequest configclusterName(String configclusterName) {
    this.configclusterName = configclusterName;
    return this;
  }

   /**
   * Get configclusterName
   * @return configclusterName
  **/
  @ApiModelProperty(value = "")
  public String getConfigclusterName() {
    return configclusterName;
  }

  public void setConfigclusterName(String configclusterName) {
    this.configclusterName = configclusterName;
  }

  public ConfigurationRequest type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ConfigurationRequest version(Long version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public Long getVersion() {
    return version;
  }

  public void setVersion(Long version) {
    this.version = version;
  }

  public ConfigurationRequest properties(Map<String, String> properties) {
    this.properties = properties;
    return this;
  }

  public ConfigurationRequest putPropertiesItem(String key, String propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<String, String>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getProperties() {
    return properties;
  }

  public void setProperties(Map<String, String> properties) {
    this.properties = properties;
  }

  public ConfigurationRequest tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  @ApiModelProperty(value = "")
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public ConfigurationRequest propertiesAttributes(Map<String, Map<String, String>> propertiesAttributes) {
    this.propertiesAttributes = propertiesAttributes;
    return this;
  }

  public ConfigurationRequest putPropertiesAttributesItem(String key, Map<String, String> propertiesAttributesItem) {
    if (this.propertiesAttributes == null) {
      this.propertiesAttributes = new HashMap<String, Map<String, String>>();
    }
    this.propertiesAttributes.put(key, propertiesAttributesItem);
    return this;
  }

   /**
   * Get propertiesAttributes
   * @return propertiesAttributes
  **/
  @ApiModelProperty(value = "")
  public Map<String, Map<String, String>> getPropertiesAttributes() {
    return propertiesAttributes;
  }

  public void setPropertiesAttributes(Map<String, Map<String, String>> propertiesAttributes) {
    this.propertiesAttributes = propertiesAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigurationRequest configurationRequest = (ConfigurationRequest) o;
    return Objects.equals(this.configclusterName, configurationRequest.configclusterName) &&
        Objects.equals(this.type, configurationRequest.type) &&
        Objects.equals(this.version, configurationRequest.version) &&
        Objects.equals(this.properties, configurationRequest.properties) &&
        Objects.equals(this.tag, configurationRequest.tag) &&
        Objects.equals(this.propertiesAttributes, configurationRequest.propertiesAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configclusterName, type, version, properties, tag, propertiesAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigurationRequest {\n");
    
    sb.append("    configclusterName: ").append(toIndentedString(configclusterName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    propertiesAttributes: ").append(toIndentedString(propertiesAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

