/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DiskInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class DiskInfo {
  @SerializedName("available")
  private String available = null;

  @SerializedName("device")
  private String device = null;

  @SerializedName("used")
  private String used = null;

  @SerializedName("percent")
  private String percent = null;

  @SerializedName("size")
  private String size = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("mountpoint")
  private String mountpoint = null;

  public DiskInfo available(String available) {
    this.available = available;
    return this;
  }

   /**
   * Get available
   * @return available
  **/
  @ApiModelProperty(value = "")
  public String getAvailable() {
    return available;
  }

  public void setAvailable(String available) {
    this.available = available;
  }

  public DiskInfo device(String device) {
    this.device = device;
    return this;
  }

   /**
   * Get device
   * @return device
  **/
  @ApiModelProperty(value = "")
  public String getDevice() {
    return device;
  }

  public void setDevice(String device) {
    this.device = device;
  }

  public DiskInfo used(String used) {
    this.used = used;
    return this;
  }

   /**
   * Get used
   * @return used
  **/
  @ApiModelProperty(value = "")
  public String getUsed() {
    return used;
  }

  public void setUsed(String used) {
    this.used = used;
  }

  public DiskInfo percent(String percent) {
    this.percent = percent;
    return this;
  }

   /**
   * Get percent
   * @return percent
  **/
  @ApiModelProperty(value = "")
  public String getPercent() {
    return percent;
  }

  public void setPercent(String percent) {
    this.percent = percent;
  }

  public DiskInfo size(String size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @ApiModelProperty(value = "")
  public String getSize() {
    return size;
  }

  public void setSize(String size) {
    this.size = size;
  }

  public DiskInfo type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public DiskInfo mountpoint(String mountpoint) {
    this.mountpoint = mountpoint;
    return this;
  }

   /**
   * Get mountpoint
   * @return mountpoint
  **/
  @ApiModelProperty(value = "")
  public String getMountpoint() {
    return mountpoint;
  }

  public void setMountpoint(String mountpoint) {
    this.mountpoint = mountpoint;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiskInfo diskInfo = (DiskInfo) o;
    return Objects.equals(this.available, diskInfo.available) &&
        Objects.equals(this.device, diskInfo.device) &&
        Objects.equals(this.used, diskInfo.used) &&
        Objects.equals(this.percent, diskInfo.percent) &&
        Objects.equals(this.size, diskInfo.size) &&
        Objects.equals(this.type, diskInfo.type) &&
        Objects.equals(this.mountpoint, diskInfo.mountpoint);
  }

  @Override
  public int hashCode() {
    return Objects.hash(available, device, used, percent, size, type, mountpoint);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiskInfo {\n");
    
    sb.append("    available: ").append(toIndentedString(available)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    used: ").append(toIndentedString(used)).append("\n");
    sb.append("    percent: ").append(toIndentedString(percent)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    mountpoint: ").append(toIndentedString(mountpoint)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

