/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ExtensionLinkResponseInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class ExtensionLinkResponseInfo {
  @SerializedName("link_id")
  private String linkId = null;

  @SerializedName("stack_name")
  private String stackName = null;

  @SerializedName("stack_version")
  private String stackVersion = null;

  @SerializedName("extension_name")
  private String extensionName = null;

  @SerializedName("extension_version")
  private String extensionVersion = null;

  public ExtensionLinkResponseInfo linkId(String linkId) {
    this.linkId = linkId;
    return this;
  }

   /**
   * Get linkId
   * @return linkId
  **/
  @ApiModelProperty(value = "")
  public String getLinkId() {
    return linkId;
  }

  public void setLinkId(String linkId) {
    this.linkId = linkId;
  }

  public ExtensionLinkResponseInfo stackName(String stackName) {
    this.stackName = stackName;
    return this;
  }

   /**
   * Get stackName
   * @return stackName
  **/
  @ApiModelProperty(value = "")
  public String getStackName() {
    return stackName;
  }

  public void setStackName(String stackName) {
    this.stackName = stackName;
  }

  public ExtensionLinkResponseInfo stackVersion(String stackVersion) {
    this.stackVersion = stackVersion;
    return this;
  }

   /**
   * Get stackVersion
   * @return stackVersion
  **/
  @ApiModelProperty(value = "")
  public String getStackVersion() {
    return stackVersion;
  }

  public void setStackVersion(String stackVersion) {
    this.stackVersion = stackVersion;
  }

  public ExtensionLinkResponseInfo extensionName(String extensionName) {
    this.extensionName = extensionName;
    return this;
  }

   /**
   * Get extensionName
   * @return extensionName
  **/
  @ApiModelProperty(value = "")
  public String getExtensionName() {
    return extensionName;
  }

  public void setExtensionName(String extensionName) {
    this.extensionName = extensionName;
  }

  public ExtensionLinkResponseInfo extensionVersion(String extensionVersion) {
    this.extensionVersion = extensionVersion;
    return this;
  }

   /**
   * Get extensionVersion
   * @return extensionVersion
  **/
  @ApiModelProperty(value = "")
  public String getExtensionVersion() {
    return extensionVersion;
  }

  public void setExtensionVersion(String extensionVersion) {
    this.extensionVersion = extensionVersion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtensionLinkResponseInfo extensionLinkResponseInfo = (ExtensionLinkResponseInfo) o;
    return Objects.equals(this.linkId, extensionLinkResponseInfo.linkId) &&
        Objects.equals(this.stackName, extensionLinkResponseInfo.stackName) &&
        Objects.equals(this.stackVersion, extensionLinkResponseInfo.stackVersion) &&
        Objects.equals(this.extensionName, extensionLinkResponseInfo.extensionName) &&
        Objects.equals(this.extensionVersion, extensionLinkResponseInfo.extensionVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linkId, stackName, stackVersion, extensionName, extensionVersion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtensionLinkResponseInfo {\n");
    
    sb.append("    linkId: ").append(toIndentedString(linkId)).append("\n");
    sb.append("    stackName: ").append(toIndentedString(stackName)).append("\n");
    sb.append("    stackVersion: ").append(toIndentedString(stackVersion)).append("\n");
    sb.append("    extensionName: ").append(toIndentedString(extensionName)).append("\n");
    sb.append("    extensionVersion: ").append(toIndentedString(extensionVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

