/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * HostConfig
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class HostConfig {
  @SerializedName("configGroupOverrides")
  private Map<String, String> configGroupOverrides = null;

  @SerializedName("defaultVersionTag")
  private String defaultVersionTag = null;

  public HostConfig configGroupOverrides(Map<String, String> configGroupOverrides) {
    this.configGroupOverrides = configGroupOverrides;
    return this;
  }

  public HostConfig putConfigGroupOverridesItem(String key, String configGroupOverridesItem) {
    if (this.configGroupOverrides == null) {
      this.configGroupOverrides = new HashMap<String, String>();
    }
    this.configGroupOverrides.put(key, configGroupOverridesItem);
    return this;
  }

   /**
   * Get configGroupOverrides
   * @return configGroupOverrides
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getConfigGroupOverrides() {
    return configGroupOverrides;
  }

  public void setConfigGroupOverrides(Map<String, String> configGroupOverrides) {
    this.configGroupOverrides = configGroupOverrides;
  }

  public HostConfig defaultVersionTag(String defaultVersionTag) {
    this.defaultVersionTag = defaultVersionTag;
    return this;
  }

   /**
   * Get defaultVersionTag
   * @return defaultVersionTag
  **/
  @ApiModelProperty(value = "")
  public String getDefaultVersionTag() {
    return defaultVersionTag;
  }

  public void setDefaultVersionTag(String defaultVersionTag) {
    this.defaultVersionTag = defaultVersionTag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HostConfig hostConfig = (HostConfig) o;
    return Objects.equals(this.configGroupOverrides, hostConfig.configGroupOverrides) &&
        Objects.equals(this.defaultVersionTag, hostConfig.defaultVersionTag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configGroupOverrides, defaultVersionTag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HostConfig {\n");
    
    sb.append("    configGroupOverrides: ").append(toIndentedString(configGroupOverrides)).append("\n");
    sb.append("    defaultVersionTag: ").append(toIndentedString(defaultVersionTag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

