/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import sunbox.sdp.ambari.client.model.ConfigurationRequest;

/**
 * HostRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class HostRequest {
  @SerializedName("host_name")
  private String hostName = null;

  @SerializedName("rack_info")
  private String rackInfo = null;

  @SerializedName("desired_configs")
  private List<ConfigurationRequest> desiredConfigs = null;

  @SerializedName("maintenance_state")
  private String maintenanceState = null;

  @SerializedName("blueprint")
  private String blueprint = null;

  @SerializedName("public_host_name")
  private String publicHostName = null;

  @SerializedName("host_group")
  private String hostGroup = null;

  public HostRequest hostName(String hostName) {
    this.hostName = hostName;
    return this;
  }

   /**
   * Get hostName
   * @return hostName
  **/
  @ApiModelProperty(value = "")
  public String getHostName() {
    return hostName;
  }

  public void setHostName(String hostName) {
    this.hostName = hostName;
  }

  public HostRequest rackInfo(String rackInfo) {
    this.rackInfo = rackInfo;
    return this;
  }

   /**
   * Get rackInfo
   * @return rackInfo
  **/
  @ApiModelProperty(value = "")
  public String getRackInfo() {
    return rackInfo;
  }

  public void setRackInfo(String rackInfo) {
    this.rackInfo = rackInfo;
  }

  public HostRequest desiredConfigs(List<ConfigurationRequest> desiredConfigs) {
    this.desiredConfigs = desiredConfigs;
    return this;
  }

  public HostRequest addDesiredConfigsItem(ConfigurationRequest desiredConfigsItem) {
    if (this.desiredConfigs == null) {
      this.desiredConfigs = new ArrayList<ConfigurationRequest>();
    }
    this.desiredConfigs.add(desiredConfigsItem);
    return this;
  }

   /**
   * Get desiredConfigs
   * @return desiredConfigs
  **/
  @ApiModelProperty(value = "")
  public List<ConfigurationRequest> getDesiredConfigs() {
    return desiredConfigs;
  }

  public void setDesiredConfigs(List<ConfigurationRequest> desiredConfigs) {
    this.desiredConfigs = desiredConfigs;
  }

  public HostRequest maintenanceState(String maintenanceState) {
    this.maintenanceState = maintenanceState;
    return this;
  }

   /**
   * Get maintenanceState
   * @return maintenanceState
  **/
  @ApiModelProperty(value = "")
  public String getMaintenanceState() {
    return maintenanceState;
  }

  public void setMaintenanceState(String maintenanceState) {
    this.maintenanceState = maintenanceState;
  }

  public HostRequest blueprint(String blueprint) {
    this.blueprint = blueprint;
    return this;
  }

   /**
   * Get blueprint
   * @return blueprint
  **/
  @ApiModelProperty(value = "")
  public String getBlueprint() {
    return blueprint;
  }

  public void setBlueprint(String blueprint) {
    this.blueprint = blueprint;
  }

  public HostRequest publicHostName(String publicHostName) {
    this.publicHostName = publicHostName;
    return this;
  }

   /**
   * Get publicHostName
   * @return publicHostName
  **/
  @ApiModelProperty(value = "")
  public String getPublicHostName() {
    return publicHostName;
  }

  public void setPublicHostName(String publicHostName) {
    this.publicHostName = publicHostName;
  }

  public HostRequest hostGroup(String hostGroup) {
    this.hostGroup = hostGroup;
    return this;
  }

   /**
   * Get hostGroup
   * @return hostGroup
  **/
  @ApiModelProperty(value = "")
  public String getHostGroup() {
    return hostGroup;
  }

  public void setHostGroup(String hostGroup) {
    this.hostGroup = hostGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HostRequest hostRequest = (HostRequest) o;
    return Objects.equals(this.hostName, hostRequest.hostName) &&
        Objects.equals(this.rackInfo, hostRequest.rackInfo) &&
        Objects.equals(this.desiredConfigs, hostRequest.desiredConfigs) &&
        Objects.equals(this.maintenanceState, hostRequest.maintenanceState) &&
        Objects.equals(this.blueprint, hostRequest.blueprint) &&
        Objects.equals(this.publicHostName, hostRequest.publicHostName) &&
        Objects.equals(this.hostGroup, hostRequest.hostGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hostName, rackInfo, desiredConfigs, maintenanceState, blueprint, publicHostName, hostGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HostRequest {\n");
    
    sb.append("    hostName: ").append(toIndentedString(hostName)).append("\n");
    sb.append("    rackInfo: ").append(toIndentedString(rackInfo)).append("\n");
    sb.append("    desiredConfigs: ").append(toIndentedString(desiredConfigs)).append("\n");
    sb.append("    maintenanceState: ").append(toIndentedString(maintenanceState)).append("\n");
    sb.append("    blueprint: ").append(toIndentedString(blueprint)).append("\n");
    sb.append("    publicHostName: ").append(toIndentedString(publicHostName)).append("\n");
    sb.append("    hostGroup: ").append(toIndentedString(hostGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

