/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import sunbox.sdp.ambari.client.model.HostComponentComponent;
import sunbox.sdp.ambari.client.model.HostComponentHost;
import sunbox.sdp.ambari.client.model.HostComponentMetrics;
import sunbox.sdp.ambari.client.model.HostComponentProcesses;
import sunbox.sdp.ambari.client.model.ServiceComponentHostResponse;

/**
 * HostComponentSwagger
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class HostComponentSwagger {
  @SerializedName("component")
  private List<HostComponentComponent> component = null;

  @SerializedName("host")
  private HostComponentHost host = null;

  @SerializedName("HostRoles")
  private ServiceComponentHostResponse hostRoles = null;

  @SerializedName("metrics")
  private HostComponentMetrics metrics = null;

  @SerializedName("processes")
  private List<HostComponentProcesses> processes = null;

  public HostComponentSwagger component(List<HostComponentComponent> component) {
    this.component = component;
    return this;
  }

  public HostComponentSwagger addComponentItem(HostComponentComponent componentItem) {
    if (this.component == null) {
      this.component = new ArrayList<HostComponentComponent>();
    }
    this.component.add(componentItem);
    return this;
  }

   /**
   * Get component
   * @return component
  **/
  @ApiModelProperty(value = "")
  public List<HostComponentComponent> getComponent() {
    return component;
  }

  public void setComponent(List<HostComponentComponent> component) {
    this.component = component;
  }

  public HostComponentSwagger host(HostComponentHost host) {
    this.host = host;
    return this;
  }

   /**
   * Get host
   * @return host
  **/
  @ApiModelProperty(value = "")
  public HostComponentHost getHost() {
    return host;
  }

  public void setHost(HostComponentHost host) {
    this.host = host;
  }

  public HostComponentSwagger hostRoles(ServiceComponentHostResponse hostRoles) {
    this.hostRoles = hostRoles;
    return this;
  }

   /**
   * Get hostRoles
   * @return hostRoles
  **/
  @ApiModelProperty(value = "")
  public ServiceComponentHostResponse getHostRoles() {
    return hostRoles;
  }

  public void setHostRoles(ServiceComponentHostResponse hostRoles) {
    this.hostRoles = hostRoles;
  }

  public HostComponentSwagger metrics(HostComponentMetrics metrics) {
    this.metrics = metrics;
    return this;
  }

   /**
   * Get metrics
   * @return metrics
  **/
  @ApiModelProperty(value = "")
  public HostComponentMetrics getMetrics() {
    return metrics;
  }

  public void setMetrics(HostComponentMetrics metrics) {
    this.metrics = metrics;
  }

  public HostComponentSwagger processes(List<HostComponentProcesses> processes) {
    this.processes = processes;
    return this;
  }

  public HostComponentSwagger addProcessesItem(HostComponentProcesses processesItem) {
    if (this.processes == null) {
      this.processes = new ArrayList<HostComponentProcesses>();
    }
    this.processes.add(processesItem);
    return this;
  }

   /**
   * Get processes
   * @return processes
  **/
  @ApiModelProperty(value = "")
  public List<HostComponentProcesses> getProcesses() {
    return processes;
  }

  public void setProcesses(List<HostComponentProcesses> processes) {
    this.processes = processes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HostComponentSwagger hostComponentSwagger = (HostComponentSwagger) o;
    return Objects.equals(this.component, hostComponentSwagger.component) &&
        Objects.equals(this.host, hostComponentSwagger.host) &&
        Objects.equals(this.hostRoles, hostComponentSwagger.hostRoles) &&
        Objects.equals(this.metrics, hostComponentSwagger.metrics) &&
        Objects.equals(this.processes, hostComponentSwagger.processes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(component, host, hostRoles, metrics, processes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HostComponentSwagger {\n");
    
    sb.append("    component: ").append(toIndentedString(component)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    hostRoles: ").append(toIndentedString(hostRoles)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    processes: ").append(toIndentedString(processes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

