/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * HostComponentProcessResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class HostComponentProcessResponse {
  @SerializedName("cluster_name")
  private String clusterName = null;

  @SerializedName("host_name")
  private String hostName = null;

  @SerializedName("component_name")
  private String componentName = null;

  @SerializedName("valueMap")
  private Map<String, String> valueMap = null;

  public HostComponentProcessResponse clusterName(String clusterName) {
    this.clusterName = clusterName;
    return this;
  }

   /**
   * Get clusterName
   * @return clusterName
  **/
  @ApiModelProperty(value = "")
  public String getClusterName() {
    return clusterName;
  }

  public void setClusterName(String clusterName) {
    this.clusterName = clusterName;
  }

  public HostComponentProcessResponse hostName(String hostName) {
    this.hostName = hostName;
    return this;
  }

   /**
   * Get hostName
   * @return hostName
  **/
  @ApiModelProperty(value = "")
  public String getHostName() {
    return hostName;
  }

  public void setHostName(String hostName) {
    this.hostName = hostName;
  }

  public HostComponentProcessResponse componentName(String componentName) {
    this.componentName = componentName;
    return this;
  }

   /**
   * Get componentName
   * @return componentName
  **/
  @ApiModelProperty(value = "")
  public String getComponentName() {
    return componentName;
  }

  public void setComponentName(String componentName) {
    this.componentName = componentName;
  }

  public HostComponentProcessResponse valueMap(Map<String, String> valueMap) {
    this.valueMap = valueMap;
    return this;
  }

  public HostComponentProcessResponse putValueMapItem(String key, String valueMapItem) {
    if (this.valueMap == null) {
      this.valueMap = new HashMap<String, String>();
    }
    this.valueMap.put(key, valueMapItem);
    return this;
  }

   /**
   * Get valueMap
   * @return valueMap
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getValueMap() {
    return valueMap;
  }

  public void setValueMap(Map<String, String> valueMap) {
    this.valueMap = valueMap;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HostComponentProcessResponse hostComponentProcessResponse = (HostComponentProcessResponse) o;
    return Objects.equals(this.clusterName, hostComponentProcessResponse.clusterName) &&
        Objects.equals(this.hostName, hostComponentProcessResponse.hostName) &&
        Objects.equals(this.componentName, hostComponentProcessResponse.componentName) &&
        Objects.equals(this.valueMap, hostComponentProcessResponse.valueMap);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clusterName, hostName, componentName, valueMap);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HostComponentProcessResponse {\n");
    
    sb.append("    clusterName: ").append(toIndentedString(clusterName)).append("\n");
    sb.append("    hostName: ").append(toIndentedString(hostName)).append("\n");
    sb.append("    componentName: ").append(toIndentedString(componentName)).append("\n");
    sb.append("    valueMap: ").append(toIndentedString(valueMap)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

