/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Host
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class Host {
  @SerializedName("httpProperty")
  private String httpProperty = null;

  @SerializedName("httpsProperty")
  private String httpsProperty = null;

  @SerializedName("site")
  private String site = null;

  public Host httpProperty(String httpProperty) {
    this.httpProperty = httpProperty;
    return this;
  }

   /**
   * Get httpProperty
   * @return httpProperty
  **/
  @ApiModelProperty(value = "")
  public String getHttpProperty() {
    return httpProperty;
  }

  public void setHttpProperty(String httpProperty) {
    this.httpProperty = httpProperty;
  }

  public Host httpsProperty(String httpsProperty) {
    this.httpsProperty = httpsProperty;
    return this;
  }

   /**
   * Get httpsProperty
   * @return httpsProperty
  **/
  @ApiModelProperty(value = "")
  public String getHttpsProperty() {
    return httpsProperty;
  }

  public void setHttpsProperty(String httpsProperty) {
    this.httpsProperty = httpsProperty;
  }

  public Host site(String site) {
    this.site = site;
    return this;
  }

   /**
   * Get site
   * @return site
  **/
  @ApiModelProperty(value = "")
  public String getSite() {
    return site;
  }

  public void setSite(String site) {
    this.site = site;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Host host = (Host) o;
    return Objects.equals(this.httpProperty, host.httpProperty) &&
        Objects.equals(this.httpsProperty, host.httpsProperty) &&
        Objects.equals(this.site, host.site);
  }

  @Override
  public int hashCode() {
    return Objects.hash(httpProperty, httpsProperty, site);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Host {\n");
    
    sb.append("    httpProperty: ").append(toIndentedString(httpProperty)).append("\n");
    sb.append("    httpsProperty: ").append(toIndentedString(httpsProperty)).append("\n");
    sb.append("    site: ").append(toIndentedString(site)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

