/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PrivilegeResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class PrivilegeResponse {
  @SerializedName("permission_label")
  private String permissionLabel = null;

  @SerializedName("privilege_id")
  private Integer privilegeId = null;

  @SerializedName("permission_name")
  private String permissionName = null;

  /**
   * Gets or Sets principalType
   */
  @JsonAdapter(PrincipalTypeEnum.Adapter.class)
  public enum PrincipalTypeEnum {
    USER("USER"),
    
    GROUP("GROUP"),
    
    ROLE("ROLE");

    private String value;

    PrincipalTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PrincipalTypeEnum fromValue(String text) {
      for (PrincipalTypeEnum b : PrincipalTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<PrincipalTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PrincipalTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PrincipalTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return PrincipalTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("principal_type")
  private PrincipalTypeEnum principalType = null;

  @SerializedName("principal_name")
  private String principalName = null;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    AMBARI("AMBARI"),
    
    CLUSTER("CLUSTER"),
    
    VIEW("VIEW");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("cluster_name")
  private String clusterName = null;

  @SerializedName("view_name")
  private String viewName = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("instance_name")
  private String instanceName = null;

  public PrivilegeResponse permissionLabel(String permissionLabel) {
    this.permissionLabel = permissionLabel;
    return this;
  }

   /**
   * Get permissionLabel
   * @return permissionLabel
  **/
  @ApiModelProperty(value = "")
  public String getPermissionLabel() {
    return permissionLabel;
  }

  public void setPermissionLabel(String permissionLabel) {
    this.permissionLabel = permissionLabel;
  }

  public PrivilegeResponse privilegeId(Integer privilegeId) {
    this.privilegeId = privilegeId;
    return this;
  }

   /**
   * Get privilegeId
   * @return privilegeId
  **/
  @ApiModelProperty(value = "")
  public Integer getPrivilegeId() {
    return privilegeId;
  }

  public void setPrivilegeId(Integer privilegeId) {
    this.privilegeId = privilegeId;
  }

  public PrivilegeResponse permissionName(String permissionName) {
    this.permissionName = permissionName;
    return this;
  }

   /**
   * Get permissionName
   * @return permissionName
  **/
  @ApiModelProperty(value = "")
  public String getPermissionName() {
    return permissionName;
  }

  public void setPermissionName(String permissionName) {
    this.permissionName = permissionName;
  }

  public PrivilegeResponse principalType(PrincipalTypeEnum principalType) {
    this.principalType = principalType;
    return this;
  }

   /**
   * Get principalType
   * @return principalType
  **/
  @ApiModelProperty(value = "")
  public PrincipalTypeEnum getPrincipalType() {
    return principalType;
  }

  public void setPrincipalType(PrincipalTypeEnum principalType) {
    this.principalType = principalType;
  }

  public PrivilegeResponse principalName(String principalName) {
    this.principalName = principalName;
    return this;
  }

   /**
   * Get principalName
   * @return principalName
  **/
  @ApiModelProperty(value = "")
  public String getPrincipalName() {
    return principalName;
  }

  public void setPrincipalName(String principalName) {
    this.principalName = principalName;
  }

  public PrivilegeResponse type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public PrivilegeResponse clusterName(String clusterName) {
    this.clusterName = clusterName;
    return this;
  }

   /**
   * Get clusterName
   * @return clusterName
  **/
  @ApiModelProperty(value = "")
  public String getClusterName() {
    return clusterName;
  }

  public void setClusterName(String clusterName) {
    this.clusterName = clusterName;
  }

  public PrivilegeResponse viewName(String viewName) {
    this.viewName = viewName;
    return this;
  }

   /**
   * Get viewName
   * @return viewName
  **/
  @ApiModelProperty(value = "")
  public String getViewName() {
    return viewName;
  }

  public void setViewName(String viewName) {
    this.viewName = viewName;
  }

  public PrivilegeResponse version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public PrivilegeResponse instanceName(String instanceName) {
    this.instanceName = instanceName;
    return this;
  }

   /**
   * Get instanceName
   * @return instanceName
  **/
  @ApiModelProperty(value = "")
  public String getInstanceName() {
    return instanceName;
  }

  public void setInstanceName(String instanceName) {
    this.instanceName = instanceName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrivilegeResponse privilegeResponse = (PrivilegeResponse) o;
    return Objects.equals(this.permissionLabel, privilegeResponse.permissionLabel) &&
        Objects.equals(this.privilegeId, privilegeResponse.privilegeId) &&
        Objects.equals(this.permissionName, privilegeResponse.permissionName) &&
        Objects.equals(this.principalType, privilegeResponse.principalType) &&
        Objects.equals(this.principalName, privilegeResponse.principalName) &&
        Objects.equals(this.type, privilegeResponse.type) &&
        Objects.equals(this.clusterName, privilegeResponse.clusterName) &&
        Objects.equals(this.viewName, privilegeResponse.viewName) &&
        Objects.equals(this.version, privilegeResponse.version) &&
        Objects.equals(this.instanceName, privilegeResponse.instanceName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(permissionLabel, privilegeId, permissionName, principalType, principalName, type, clusterName, viewName, version, instanceName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrivilegeResponse {\n");
    
    sb.append("    permissionLabel: ").append(toIndentedString(permissionLabel)).append("\n");
    sb.append("    privilegeId: ").append(toIndentedString(privilegeId)).append("\n");
    sb.append("    permissionName: ").append(toIndentedString(permissionName)).append("\n");
    sb.append("    principalType: ").append(toIndentedString(principalType)).append("\n");
    sb.append("    principalName: ").append(toIndentedString(principalName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    clusterName: ").append(toIndentedString(clusterName)).append("\n");
    sb.append("    viewName: ").append(toIndentedString(viewName)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    instanceName: ").append(toIndentedString(instanceName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

