/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import sunbox.sdp.ambari.client.model.QuickLinksConfiguration;

/**
 * QuickLinksResponseInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class QuickLinksResponseInfo {
  @SerializedName("default")
  private Boolean _default = false;

  @SerializedName("file_name")
  private String fileName = null;

  @SerializedName("stack_version")
  private String stackVersion = null;

  @SerializedName("service_name")
  private String serviceName = null;

  @SerializedName("stack_name")
  private String stackName = null;

  @SerializedName("quicklink_data")
  private QuickLinksConfiguration quicklinkData = null;

  public QuickLinksResponseInfo _default(Boolean _default) {
    this._default = _default;
    return this;
  }

   /**
   * Get _default
   * @return _default
  **/
  @ApiModelProperty(value = "")
  public Boolean isDefault() {
    return _default;
  }

  public void setDefault(Boolean _default) {
    this._default = _default;
  }

  public QuickLinksResponseInfo fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * Get fileName
   * @return fileName
  **/
  @ApiModelProperty(value = "")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public QuickLinksResponseInfo stackVersion(String stackVersion) {
    this.stackVersion = stackVersion;
    return this;
  }

   /**
   * Get stackVersion
   * @return stackVersion
  **/
  @ApiModelProperty(value = "")
  public String getStackVersion() {
    return stackVersion;
  }

  public void setStackVersion(String stackVersion) {
    this.stackVersion = stackVersion;
  }

  public QuickLinksResponseInfo serviceName(String serviceName) {
    this.serviceName = serviceName;
    return this;
  }

   /**
   * Get serviceName
   * @return serviceName
  **/
  @ApiModelProperty(value = "")
  public String getServiceName() {
    return serviceName;
  }

  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }

  public QuickLinksResponseInfo stackName(String stackName) {
    this.stackName = stackName;
    return this;
  }

   /**
   * Get stackName
   * @return stackName
  **/
  @ApiModelProperty(value = "")
  public String getStackName() {
    return stackName;
  }

  public void setStackName(String stackName) {
    this.stackName = stackName;
  }

  public QuickLinksResponseInfo quicklinkData(QuickLinksConfiguration quicklinkData) {
    this.quicklinkData = quicklinkData;
    return this;
  }

   /**
   * Get quicklinkData
   * @return quicklinkData
  **/
  @ApiModelProperty(value = "")
  public QuickLinksConfiguration getQuicklinkData() {
    return quicklinkData;
  }

  public void setQuicklinkData(QuickLinksConfiguration quicklinkData) {
    this.quicklinkData = quicklinkData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuickLinksResponseInfo quickLinksResponseInfo = (QuickLinksResponseInfo) o;
    return Objects.equals(this._default, quickLinksResponseInfo._default) &&
        Objects.equals(this.fileName, quickLinksResponseInfo.fileName) &&
        Objects.equals(this.stackVersion, quickLinksResponseInfo.stackVersion) &&
        Objects.equals(this.serviceName, quickLinksResponseInfo.serviceName) &&
        Objects.equals(this.stackName, quickLinksResponseInfo.stackName) &&
        Objects.equals(this.quicklinkData, quickLinksResponseInfo.quicklinkData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_default, fileName, stackVersion, serviceName, stackName, quicklinkData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuickLinksResponseInfo {\n");
    
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    stackVersion: ").append(toIndentedString(stackVersion)).append("\n");
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("    stackName: ").append(toIndentedString(stackName)).append("\n");
    sb.append("    quicklinkData: ").append(toIndentedString(quicklinkData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

