/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Release
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class Release {
  /**
   * Gets or Sets repositoryType
   */
  @JsonAdapter(RepositoryTypeEnum.Adapter.class)
  public enum RepositoryTypeEnum {
    STANDARD("STANDARD"),
    
    PATCH("PATCH"),
    
    MAINT("MAINT"),
    
    SERVICE("SERVICE");

    private String value;

    RepositoryTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RepositoryTypeEnum fromValue(String text) {
      for (RepositoryTypeEnum b : RepositoryTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<RepositoryTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RepositoryTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RepositoryTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return RepositoryTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("repositoryType")
  private RepositoryTypeEnum repositoryType = null;

  @SerializedName("stackId")
  private String stackId = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("build")
  private String build = null;

  @SerializedName("compatibleWith")
  private String compatibleWith = null;

  @SerializedName("releaseNotes")
  private String releaseNotes = null;

  @SerializedName("display")
  private String display = null;

  @SerializedName("fullVersion")
  private String fullVersion = null;

  public Release repositoryType(RepositoryTypeEnum repositoryType) {
    this.repositoryType = repositoryType;
    return this;
  }

   /**
   * Get repositoryType
   * @return repositoryType
  **/
  @ApiModelProperty(value = "")
  public RepositoryTypeEnum getRepositoryType() {
    return repositoryType;
  }

  public void setRepositoryType(RepositoryTypeEnum repositoryType) {
    this.repositoryType = repositoryType;
  }

  public Release stackId(String stackId) {
    this.stackId = stackId;
    return this;
  }

   /**
   * Get stackId
   * @return stackId
  **/
  @ApiModelProperty(value = "")
  public String getStackId() {
    return stackId;
  }

  public void setStackId(String stackId) {
    this.stackId = stackId;
  }

  public Release version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public Release build(String build) {
    this.build = build;
    return this;
  }

   /**
   * Get build
   * @return build
  **/
  @ApiModelProperty(value = "")
  public String getBuild() {
    return build;
  }

  public void setBuild(String build) {
    this.build = build;
  }

  public Release compatibleWith(String compatibleWith) {
    this.compatibleWith = compatibleWith;
    return this;
  }

   /**
   * Get compatibleWith
   * @return compatibleWith
  **/
  @ApiModelProperty(value = "")
  public String getCompatibleWith() {
    return compatibleWith;
  }

  public void setCompatibleWith(String compatibleWith) {
    this.compatibleWith = compatibleWith;
  }

  public Release releaseNotes(String releaseNotes) {
    this.releaseNotes = releaseNotes;
    return this;
  }

   /**
   * Get releaseNotes
   * @return releaseNotes
  **/
  @ApiModelProperty(value = "")
  public String getReleaseNotes() {
    return releaseNotes;
  }

  public void setReleaseNotes(String releaseNotes) {
    this.releaseNotes = releaseNotes;
  }

  public Release display(String display) {
    this.display = display;
    return this;
  }

   /**
   * Get display
   * @return display
  **/
  @ApiModelProperty(value = "")
  public String getDisplay() {
    return display;
  }

  public void setDisplay(String display) {
    this.display = display;
  }

  public Release fullVersion(String fullVersion) {
    this.fullVersion = fullVersion;
    return this;
  }

   /**
   * Get fullVersion
   * @return fullVersion
  **/
  @ApiModelProperty(value = "")
  public String getFullVersion() {
    return fullVersion;
  }

  public void setFullVersion(String fullVersion) {
    this.fullVersion = fullVersion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Release release = (Release) o;
    return Objects.equals(this.repositoryType, release.repositoryType) &&
        Objects.equals(this.stackId, release.stackId) &&
        Objects.equals(this.version, release.version) &&
        Objects.equals(this.build, release.build) &&
        Objects.equals(this.compatibleWith, release.compatibleWith) &&
        Objects.equals(this.releaseNotes, release.releaseNotes) &&
        Objects.equals(this.display, release.display) &&
        Objects.equals(this.fullVersion, release.fullVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(repositoryType, stackId, version, build, compatibleWith, releaseNotes, display, fullVersion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Release {\n");
    
    sb.append("    repositoryType: ").append(toIndentedString(repositoryType)).append("\n");
    sb.append("    stackId: ").append(toIndentedString(stackId)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    build: ").append(toIndentedString(build)).append("\n");
    sb.append("    compatibleWith: ").append(toIndentedString(compatibleWith)).append("\n");
    sb.append("    releaseNotes: ").append(toIndentedString(releaseNotes)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    fullVersion: ").append(toIndentedString(fullVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

