/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import sunbox.sdp.ambari.client.model.RepoOsEntity;
import sunbox.sdp.ambari.client.model.RepositoryVersionEntity;
import sunbox.sdp.ambari.client.model.StackEntity;
import sunbox.sdp.ambari.client.model.StackId;
import sunbox.sdp.ambari.client.model.VersionDefinitionXml;

/**
 * RepositoryVersionEntity
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class RepositoryVersionEntity {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("stack")
  private StackEntity stack = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("repoOsEntities")
  private List<RepoOsEntity> repoOsEntities = null;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    STANDARD("STANDARD"),
    
    PATCH("PATCH"),
    
    MAINT("MAINT"),
    
    SERVICE("SERVICE");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("versionXml")
  private String versionXml = null;

  @SerializedName("versionUrl")
  private String versionUrl = null;

  @SerializedName("versionXsd")
  private String versionXsd = null;

  @SerializedName("resolved")
  private Boolean resolved = false;

  @SerializedName("children")
  private List<RepositoryVersionEntity> children = null;

  @SerializedName("hidden")
  private Boolean hidden = false;

  @SerializedName("stackId")
  private StackId stackId = null;

  @SerializedName("repositoryXml")
  private VersionDefinitionXml repositoryXml = null;

  @SerializedName("stackVersion")
  private String stackVersion = null;

  @SerializedName("stackName")
  private String stackName = null;

  @SerializedName("legacy")
  private Boolean legacy = false;

  @SerializedName("parentId")
  private Long parentId = null;

  public RepositoryVersionEntity id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public RepositoryVersionEntity stack(StackEntity stack) {
    this.stack = stack;
    return this;
  }

   /**
   * Get stack
   * @return stack
  **/
  @ApiModelProperty(value = "")
  public StackEntity getStack() {
    return stack;
  }

  public void setStack(StackEntity stack) {
    this.stack = stack;
  }

  public RepositoryVersionEntity version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public RepositoryVersionEntity displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public RepositoryVersionEntity repoOsEntities(List<RepoOsEntity> repoOsEntities) {
    this.repoOsEntities = repoOsEntities;
    return this;
  }

  public RepositoryVersionEntity addRepoOsEntitiesItem(RepoOsEntity repoOsEntitiesItem) {
    if (this.repoOsEntities == null) {
      this.repoOsEntities = new ArrayList<RepoOsEntity>();
    }
    this.repoOsEntities.add(repoOsEntitiesItem);
    return this;
  }

   /**
   * Get repoOsEntities
   * @return repoOsEntities
  **/
  @ApiModelProperty(value = "")
  public List<RepoOsEntity> getRepoOsEntities() {
    return repoOsEntities;
  }

  public void setRepoOsEntities(List<RepoOsEntity> repoOsEntities) {
    this.repoOsEntities = repoOsEntities;
  }

  public RepositoryVersionEntity type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public RepositoryVersionEntity versionXml(String versionXml) {
    this.versionXml = versionXml;
    return this;
  }

   /**
   * Get versionXml
   * @return versionXml
  **/
  @ApiModelProperty(value = "")
  public String getVersionXml() {
    return versionXml;
  }

  public void setVersionXml(String versionXml) {
    this.versionXml = versionXml;
  }

  public RepositoryVersionEntity versionUrl(String versionUrl) {
    this.versionUrl = versionUrl;
    return this;
  }

   /**
   * Get versionUrl
   * @return versionUrl
  **/
  @ApiModelProperty(value = "")
  public String getVersionUrl() {
    return versionUrl;
  }

  public void setVersionUrl(String versionUrl) {
    this.versionUrl = versionUrl;
  }

  public RepositoryVersionEntity versionXsd(String versionXsd) {
    this.versionXsd = versionXsd;
    return this;
  }

   /**
   * Get versionXsd
   * @return versionXsd
  **/
  @ApiModelProperty(value = "")
  public String getVersionXsd() {
    return versionXsd;
  }

  public void setVersionXsd(String versionXsd) {
    this.versionXsd = versionXsd;
  }

  public RepositoryVersionEntity resolved(Boolean resolved) {
    this.resolved = resolved;
    return this;
  }

   /**
   * Get resolved
   * @return resolved
  **/
  @ApiModelProperty(value = "")
  public Boolean isResolved() {
    return resolved;
  }

  public void setResolved(Boolean resolved) {
    this.resolved = resolved;
  }

  public RepositoryVersionEntity children(List<RepositoryVersionEntity> children) {
    this.children = children;
    return this;
  }

  public RepositoryVersionEntity addChildrenItem(RepositoryVersionEntity childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<RepositoryVersionEntity>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  @ApiModelProperty(value = "")
  public List<RepositoryVersionEntity> getChildren() {
    return children;
  }

  public void setChildren(List<RepositoryVersionEntity> children) {
    this.children = children;
  }

  public RepositoryVersionEntity hidden(Boolean hidden) {
    this.hidden = hidden;
    return this;
  }

   /**
   * Get hidden
   * @return hidden
  **/
  @ApiModelProperty(value = "")
  public Boolean isHidden() {
    return hidden;
  }

  public void setHidden(Boolean hidden) {
    this.hidden = hidden;
  }

  public RepositoryVersionEntity stackId(StackId stackId) {
    this.stackId = stackId;
    return this;
  }

   /**
   * Get stackId
   * @return stackId
  **/
  @ApiModelProperty(value = "")
  public StackId getStackId() {
    return stackId;
  }

  public void setStackId(StackId stackId) {
    this.stackId = stackId;
  }

  public RepositoryVersionEntity repositoryXml(VersionDefinitionXml repositoryXml) {
    this.repositoryXml = repositoryXml;
    return this;
  }

   /**
   * Get repositoryXml
   * @return repositoryXml
  **/
  @ApiModelProperty(value = "")
  public VersionDefinitionXml getRepositoryXml() {
    return repositoryXml;
  }

  public void setRepositoryXml(VersionDefinitionXml repositoryXml) {
    this.repositoryXml = repositoryXml;
  }

  public RepositoryVersionEntity stackVersion(String stackVersion) {
    this.stackVersion = stackVersion;
    return this;
  }

   /**
   * Get stackVersion
   * @return stackVersion
  **/
  @ApiModelProperty(value = "")
  public String getStackVersion() {
    return stackVersion;
  }

  public void setStackVersion(String stackVersion) {
    this.stackVersion = stackVersion;
  }

  public RepositoryVersionEntity stackName(String stackName) {
    this.stackName = stackName;
    return this;
  }

   /**
   * Get stackName
   * @return stackName
  **/
  @ApiModelProperty(value = "")
  public String getStackName() {
    return stackName;
  }

  public void setStackName(String stackName) {
    this.stackName = stackName;
  }

  public RepositoryVersionEntity legacy(Boolean legacy) {
    this.legacy = legacy;
    return this;
  }

   /**
   * Get legacy
   * @return legacy
  **/
  @ApiModelProperty(value = "")
  public Boolean isLegacy() {
    return legacy;
  }

  public void setLegacy(Boolean legacy) {
    this.legacy = legacy;
  }

  public RepositoryVersionEntity parentId(Long parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/
  @ApiModelProperty(value = "")
  public Long getParentId() {
    return parentId;
  }

  public void setParentId(Long parentId) {
    this.parentId = parentId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepositoryVersionEntity repositoryVersionEntity = (RepositoryVersionEntity) o;
    return Objects.equals(this.id, repositoryVersionEntity.id) &&
        Objects.equals(this.stack, repositoryVersionEntity.stack) &&
        Objects.equals(this.version, repositoryVersionEntity.version) &&
        Objects.equals(this.displayName, repositoryVersionEntity.displayName) &&
        Objects.equals(this.repoOsEntities, repositoryVersionEntity.repoOsEntities) &&
        Objects.equals(this.type, repositoryVersionEntity.type) &&
        Objects.equals(this.versionXml, repositoryVersionEntity.versionXml) &&
        Objects.equals(this.versionUrl, repositoryVersionEntity.versionUrl) &&
        Objects.equals(this.versionXsd, repositoryVersionEntity.versionXsd) &&
        Objects.equals(this.resolved, repositoryVersionEntity.resolved) &&
        Objects.equals(this.children, repositoryVersionEntity.children) &&
        Objects.equals(this.hidden, repositoryVersionEntity.hidden) &&
        Objects.equals(this.stackId, repositoryVersionEntity.stackId) &&
        Objects.equals(this.repositoryXml, repositoryVersionEntity.repositoryXml) &&
        Objects.equals(this.stackVersion, repositoryVersionEntity.stackVersion) &&
        Objects.equals(this.stackName, repositoryVersionEntity.stackName) &&
        Objects.equals(this.legacy, repositoryVersionEntity.legacy) &&
        Objects.equals(this.parentId, repositoryVersionEntity.parentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, stack, version, displayName, repoOsEntities, type, versionXml, versionUrl, versionXsd, resolved, children, hidden, stackId, repositoryXml, stackVersion, stackName, legacy, parentId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepositoryVersionEntity {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    stack: ").append(toIndentedString(stack)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    repoOsEntities: ").append(toIndentedString(repoOsEntities)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    versionXml: ").append(toIndentedString(versionXml)).append("\n");
    sb.append("    versionUrl: ").append(toIndentedString(versionUrl)).append("\n");
    sb.append("    versionXsd: ").append(toIndentedString(versionXsd)).append("\n");
    sb.append("    resolved: ").append(toIndentedString(resolved)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("    stackId: ").append(toIndentedString(stackId)).append("\n");
    sb.append("    repositoryXml: ").append(toIndentedString(repositoryXml)).append("\n");
    sb.append("    stackVersion: ").append(toIndentedString(stackVersion)).append("\n");
    sb.append("    stackName: ").append(toIndentedString(stackName)).append("\n");
    sb.append("    legacy: ").append(toIndentedString(legacy)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

