/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import sunbox.sdp.ambari.client.model.Os;
import sunbox.sdp.ambari.client.model.RepositoryInfo;

/**
 * RepositoryXml
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class RepositoryXml {
  @SerializedName("oses")
  private List<Os> oses = null;

  @SerializedName("valid")
  private Boolean valid = false;

  @SerializedName("errors")
  private List<String> errors = null;

  @SerializedName("repositories")
  private List<RepositoryInfo> repositories = null;

  @SerializedName("latestURI")
  private String latestURI = null;

  public RepositoryXml oses(List<Os> oses) {
    this.oses = oses;
    return this;
  }

  public RepositoryXml addOsesItem(Os osesItem) {
    if (this.oses == null) {
      this.oses = new ArrayList<Os>();
    }
    this.oses.add(osesItem);
    return this;
  }

   /**
   * Get oses
   * @return oses
  **/
  @ApiModelProperty(value = "")
  public List<Os> getOses() {
    return oses;
  }

  public void setOses(List<Os> oses) {
    this.oses = oses;
  }

  public RepositoryXml valid(Boolean valid) {
    this.valid = valid;
    return this;
  }

   /**
   * Get valid
   * @return valid
  **/
  @ApiModelProperty(value = "")
  public Boolean isValid() {
    return valid;
  }

  public void setValid(Boolean valid) {
    this.valid = valid;
  }

  public RepositoryXml errors(List<String> errors) {
    this.errors = errors;
    return this;
  }

  public RepositoryXml addErrorsItem(String errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<String>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @ApiModelProperty(value = "")
  public List<String> getErrors() {
    return errors;
  }

  public void setErrors(List<String> errors) {
    this.errors = errors;
  }

  public RepositoryXml repositories(List<RepositoryInfo> repositories) {
    this.repositories = repositories;
    return this;
  }

  public RepositoryXml addRepositoriesItem(RepositoryInfo repositoriesItem) {
    if (this.repositories == null) {
      this.repositories = new ArrayList<RepositoryInfo>();
    }
    this.repositories.add(repositoriesItem);
    return this;
  }

   /**
   * Get repositories
   * @return repositories
  **/
  @ApiModelProperty(value = "")
  public List<RepositoryInfo> getRepositories() {
    return repositories;
  }

  public void setRepositories(List<RepositoryInfo> repositories) {
    this.repositories = repositories;
  }

  public RepositoryXml latestURI(String latestURI) {
    this.latestURI = latestURI;
    return this;
  }

   /**
   * Get latestURI
   * @return latestURI
  **/
  @ApiModelProperty(value = "")
  public String getLatestURI() {
    return latestURI;
  }

  public void setLatestURI(String latestURI) {
    this.latestURI = latestURI;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepositoryXml repositoryXml = (RepositoryXml) o;
    return Objects.equals(this.oses, repositoryXml.oses) &&
        Objects.equals(this.valid, repositoryXml.valid) &&
        Objects.equals(this.errors, repositoryXml.errors) &&
        Objects.equals(this.repositories, repositoryXml.repositories) &&
        Objects.equals(this.latestURI, repositoryXml.latestURI);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oses, valid, errors, repositories, latestURI);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepositoryXml {\n");
    
    sb.append("    oses: ").append(toIndentedString(oses)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    repositories: ").append(toIndentedString(repositories)).append("\n");
    sb.append("    latestURI: ").append(toIndentedString(latestURI)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

