/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import sunbox.sdp.ambari.client.model.RequestResourceFilter;

/**
 * RequestStatusInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class RequestStatusInfo {
  @SerializedName("request_context")
  private String requestContext = null;

  @SerializedName("request_status")
  private String requestStatus = null;

  @SerializedName("start_time")
  private String startTime = null;

  @SerializedName("task_count")
  private Integer taskCount = null;

  @SerializedName("completed_task_count")
  private String completedTaskCount = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("cluster_name")
  private String clusterName = null;

  @SerializedName("create_time")
  private Long createTime = null;

  @SerializedName("request_schedule")
  private String requestSchedule = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("aborted_task_count")
  private Integer abortedTaskCount = null;

  @SerializedName("end_time")
  private String endTime = null;

  @SerializedName("exclusive")
  private Boolean exclusive = false;

  @SerializedName("failed_task_count")
  private Integer failedTaskCount = null;

  @SerializedName("inputs")
  private String inputs = null;

  @SerializedName("operation_level")
  private String operationLevel = null;

  @SerializedName("progress_percent")
  private Double progressPercent = null;

  @SerializedName("queued_task_count")
  private Integer queuedTaskCount = null;

  @SerializedName("request_schedule_id")
  private Long requestScheduleId = null;

  @SerializedName("resource_filters")
  private List<RequestResourceFilter> resourceFilters = null;

  public RequestStatusInfo requestContext(String requestContext) {
    this.requestContext = requestContext;
    return this;
  }

   /**
   * Get requestContext
   * @return requestContext
  **/
  @ApiModelProperty(value = "")
  public String getRequestContext() {
    return requestContext;
  }

  public void setRequestContext(String requestContext) {
    this.requestContext = requestContext;
  }

  public RequestStatusInfo requestStatus(String requestStatus) {
    this.requestStatus = requestStatus;
    return this;
  }

   /**
   * Get requestStatus
   * @return requestStatus
  **/
  @ApiModelProperty(value = "")
  public String getRequestStatus() {
    return requestStatus;
  }

  public void setRequestStatus(String requestStatus) {
    this.requestStatus = requestStatus;
  }

  public RequestStatusInfo startTime(String startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @ApiModelProperty(value = "")
  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public RequestStatusInfo taskCount(Integer taskCount) {
    this.taskCount = taskCount;
    return this;
  }

   /**
   * Get taskCount
   * @return taskCount
  **/
  @ApiModelProperty(value = "")
  public Integer getTaskCount() {
    return taskCount;
  }

  public void setTaskCount(Integer taskCount) {
    this.taskCount = taskCount;
  }

  public RequestStatusInfo completedTaskCount(String completedTaskCount) {
    this.completedTaskCount = completedTaskCount;
    return this;
  }

   /**
   * Get completedTaskCount
   * @return completedTaskCount
  **/
  @ApiModelProperty(value = "")
  public String getCompletedTaskCount() {
    return completedTaskCount;
  }

  public void setCompletedTaskCount(String completedTaskCount) {
    this.completedTaskCount = completedTaskCount;
  }

  public RequestStatusInfo type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public RequestStatusInfo clusterName(String clusterName) {
    this.clusterName = clusterName;
    return this;
  }

   /**
   * Get clusterName
   * @return clusterName
  **/
  @ApiModelProperty(value = "")
  public String getClusterName() {
    return clusterName;
  }

  public void setClusterName(String clusterName) {
    this.clusterName = clusterName;
  }

  public RequestStatusInfo createTime(Long createTime) {
    this.createTime = createTime;
    return this;
  }

   /**
   * Get createTime
   * @return createTime
  **/
  @ApiModelProperty(value = "")
  public Long getCreateTime() {
    return createTime;
  }

  public void setCreateTime(Long createTime) {
    this.createTime = createTime;
  }

  public RequestStatusInfo requestSchedule(String requestSchedule) {
    this.requestSchedule = requestSchedule;
    return this;
  }

   /**
   * Get requestSchedule
   * @return requestSchedule
  **/
  @ApiModelProperty(value = "")
  public String getRequestSchedule() {
    return requestSchedule;
  }

  public void setRequestSchedule(String requestSchedule) {
    this.requestSchedule = requestSchedule;
  }

  public RequestStatusInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RequestStatusInfo abortedTaskCount(Integer abortedTaskCount) {
    this.abortedTaskCount = abortedTaskCount;
    return this;
  }

   /**
   * Get abortedTaskCount
   * @return abortedTaskCount
  **/
  @ApiModelProperty(value = "")
  public Integer getAbortedTaskCount() {
    return abortedTaskCount;
  }

  public void setAbortedTaskCount(Integer abortedTaskCount) {
    this.abortedTaskCount = abortedTaskCount;
  }

  public RequestStatusInfo endTime(String endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @ApiModelProperty(value = "")
  public String getEndTime() {
    return endTime;
  }

  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }

  public RequestStatusInfo exclusive(Boolean exclusive) {
    this.exclusive = exclusive;
    return this;
  }

   /**
   * Get exclusive
   * @return exclusive
  **/
  @ApiModelProperty(value = "")
  public Boolean isExclusive() {
    return exclusive;
  }

  public void setExclusive(Boolean exclusive) {
    this.exclusive = exclusive;
  }

  public RequestStatusInfo failedTaskCount(Integer failedTaskCount) {
    this.failedTaskCount = failedTaskCount;
    return this;
  }

   /**
   * Get failedTaskCount
   * @return failedTaskCount
  **/
  @ApiModelProperty(value = "")
  public Integer getFailedTaskCount() {
    return failedTaskCount;
  }

  public void setFailedTaskCount(Integer failedTaskCount) {
    this.failedTaskCount = failedTaskCount;
  }

  public RequestStatusInfo inputs(String inputs) {
    this.inputs = inputs;
    return this;
  }

   /**
   * Get inputs
   * @return inputs
  **/
  @ApiModelProperty(value = "")
  public String getInputs() {
    return inputs;
  }

  public void setInputs(String inputs) {
    this.inputs = inputs;
  }

  public RequestStatusInfo operationLevel(String operationLevel) {
    this.operationLevel = operationLevel;
    return this;
  }

   /**
   * Get operationLevel
   * @return operationLevel
  **/
  @ApiModelProperty(value = "")
  public String getOperationLevel() {
    return operationLevel;
  }

  public void setOperationLevel(String operationLevel) {
    this.operationLevel = operationLevel;
  }

  public RequestStatusInfo progressPercent(Double progressPercent) {
    this.progressPercent = progressPercent;
    return this;
  }

   /**
   * Get progressPercent
   * @return progressPercent
  **/
  @ApiModelProperty(value = "")
  public Double getProgressPercent() {
    return progressPercent;
  }

  public void setProgressPercent(Double progressPercent) {
    this.progressPercent = progressPercent;
  }

  public RequestStatusInfo queuedTaskCount(Integer queuedTaskCount) {
    this.queuedTaskCount = queuedTaskCount;
    return this;
  }

   /**
   * Get queuedTaskCount
   * @return queuedTaskCount
  **/
  @ApiModelProperty(value = "")
  public Integer getQueuedTaskCount() {
    return queuedTaskCount;
  }

  public void setQueuedTaskCount(Integer queuedTaskCount) {
    this.queuedTaskCount = queuedTaskCount;
  }

  public RequestStatusInfo requestScheduleId(Long requestScheduleId) {
    this.requestScheduleId = requestScheduleId;
    return this;
  }

   /**
   * Get requestScheduleId
   * @return requestScheduleId
  **/
  @ApiModelProperty(value = "")
  public Long getRequestScheduleId() {
    return requestScheduleId;
  }

  public void setRequestScheduleId(Long requestScheduleId) {
    this.requestScheduleId = requestScheduleId;
  }

  public RequestStatusInfo resourceFilters(List<RequestResourceFilter> resourceFilters) {
    this.resourceFilters = resourceFilters;
    return this;
  }

  public RequestStatusInfo addResourceFiltersItem(RequestResourceFilter resourceFiltersItem) {
    if (this.resourceFilters == null) {
      this.resourceFilters = new ArrayList<RequestResourceFilter>();
    }
    this.resourceFilters.add(resourceFiltersItem);
    return this;
  }

   /**
   * Get resourceFilters
   * @return resourceFilters
  **/
  @ApiModelProperty(value = "")
  public List<RequestResourceFilter> getResourceFilters() {
    return resourceFilters;
  }

  public void setResourceFilters(List<RequestResourceFilter> resourceFilters) {
    this.resourceFilters = resourceFilters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestStatusInfo requestStatusInfo = (RequestStatusInfo) o;
    return Objects.equals(this.requestContext, requestStatusInfo.requestContext) &&
        Objects.equals(this.requestStatus, requestStatusInfo.requestStatus) &&
        Objects.equals(this.startTime, requestStatusInfo.startTime) &&
        Objects.equals(this.taskCount, requestStatusInfo.taskCount) &&
        Objects.equals(this.completedTaskCount, requestStatusInfo.completedTaskCount) &&
        Objects.equals(this.type, requestStatusInfo.type) &&
        Objects.equals(this.clusterName, requestStatusInfo.clusterName) &&
        Objects.equals(this.createTime, requestStatusInfo.createTime) &&
        Objects.equals(this.requestSchedule, requestStatusInfo.requestSchedule) &&
        Objects.equals(this.id, requestStatusInfo.id) &&
        Objects.equals(this.abortedTaskCount, requestStatusInfo.abortedTaskCount) &&
        Objects.equals(this.endTime, requestStatusInfo.endTime) &&
        Objects.equals(this.exclusive, requestStatusInfo.exclusive) &&
        Objects.equals(this.failedTaskCount, requestStatusInfo.failedTaskCount) &&
        Objects.equals(this.inputs, requestStatusInfo.inputs) &&
        Objects.equals(this.operationLevel, requestStatusInfo.operationLevel) &&
        Objects.equals(this.progressPercent, requestStatusInfo.progressPercent) &&
        Objects.equals(this.queuedTaskCount, requestStatusInfo.queuedTaskCount) &&
        Objects.equals(this.requestScheduleId, requestStatusInfo.requestScheduleId) &&
        Objects.equals(this.resourceFilters, requestStatusInfo.resourceFilters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestContext, requestStatus, startTime, taskCount, completedTaskCount, type, clusterName, createTime, requestSchedule, id, abortedTaskCount, endTime, exclusive, failedTaskCount, inputs, operationLevel, progressPercent, queuedTaskCount, requestScheduleId, resourceFilters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestStatusInfo {\n");
    
    sb.append("    requestContext: ").append(toIndentedString(requestContext)).append("\n");
    sb.append("    requestStatus: ").append(toIndentedString(requestStatus)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    taskCount: ").append(toIndentedString(taskCount)).append("\n");
    sb.append("    completedTaskCount: ").append(toIndentedString(completedTaskCount)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    clusterName: ").append(toIndentedString(clusterName)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    requestSchedule: ").append(toIndentedString(requestSchedule)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    abortedTaskCount: ").append(toIndentedString(abortedTaskCount)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    exclusive: ").append(toIndentedString(exclusive)).append("\n");
    sb.append("    failedTaskCount: ").append(toIndentedString(failedTaskCount)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    operationLevel: ").append(toIndentedString(operationLevel)).append("\n");
    sb.append("    progressPercent: ").append(toIndentedString(progressPercent)).append("\n");
    sb.append("    queuedTaskCount: ").append(toIndentedString(queuedTaskCount)).append("\n");
    sb.append("    requestScheduleId: ").append(toIndentedString(requestScheduleId)).append("\n");
    sb.append("    resourceFilters: ").append(toIndentedString(resourceFilters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

