/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import sunbox.sdp.ambari.client.model.RootServiceComponentResponseWrapper;
import sunbox.sdp.ambari.client.model.RootServiceResponse;

/**
 * RootServiceResponseWithComponentList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class RootServiceResponseWithComponentList {
  @SerializedName("components")
  private List<RootServiceComponentResponseWrapper> components = null;

  @SerializedName("RootService")
  private RootServiceResponse rootService = null;

  public RootServiceResponseWithComponentList components(List<RootServiceComponentResponseWrapper> components) {
    this.components = components;
    return this;
  }

  public RootServiceResponseWithComponentList addComponentsItem(RootServiceComponentResponseWrapper componentsItem) {
    if (this.components == null) {
      this.components = new ArrayList<RootServiceComponentResponseWrapper>();
    }
    this.components.add(componentsItem);
    return this;
  }

   /**
   * Get components
   * @return components
  **/
  @ApiModelProperty(value = "")
  public List<RootServiceComponentResponseWrapper> getComponents() {
    return components;
  }

  public void setComponents(List<RootServiceComponentResponseWrapper> components) {
    this.components = components;
  }

  public RootServiceResponseWithComponentList rootService(RootServiceResponse rootService) {
    this.rootService = rootService;
    return this;
  }

   /**
   * Get rootService
   * @return rootService
  **/
  @ApiModelProperty(value = "")
  public RootServiceResponse getRootService() {
    return rootService;
  }

  public void setRootService(RootServiceResponse rootService) {
    this.rootService = rootService;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootServiceResponseWithComponentList rootServiceResponseWithComponentList = (RootServiceResponseWithComponentList) o;
    return Objects.equals(this.components, rootServiceResponseWithComponentList.components) &&
        Objects.equals(this.rootService, rootServiceResponseWithComponentList.rootService);
  }

  @Override
  public int hashCode() {
    return Objects.hash(components, rootService);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootServiceResponseWithComponentList {\n");
    
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("    rootService: ").append(toIndentedString(rootService)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

