/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import sunbox.sdp.ambari.client.model.Subsection;

/**
 * Section
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class Section {
  @SerializedName("subsections")
  private List<Subsection> subsections = null;

  @SerializedName("display-name")
  private String displayName = null;

  @SerializedName("row-index")
  private String rowIndex = null;

  @SerializedName("section-rows")
  private String sectionRows = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("column-span")
  private String columnSpan = null;

  @SerializedName("section-columns")
  private String sectionColumns = null;

  @SerializedName("column-index")
  private String columnIndex = null;

  @SerializedName("row-span")
  private String rowSpan = null;

  @SerializedName("removed")
  private Boolean removed = false;

  public Section subsections(List<Subsection> subsections) {
    this.subsections = subsections;
    return this;
  }

  public Section addSubsectionsItem(Subsection subsectionsItem) {
    if (this.subsections == null) {
      this.subsections = new ArrayList<Subsection>();
    }
    this.subsections.add(subsectionsItem);
    return this;
  }

   /**
   * Get subsections
   * @return subsections
  **/
  @ApiModelProperty(value = "")
  public List<Subsection> getSubsections() {
    return subsections;
  }

  public void setSubsections(List<Subsection> subsections) {
    this.subsections = subsections;
  }

  public Section displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public Section rowIndex(String rowIndex) {
    this.rowIndex = rowIndex;
    return this;
  }

   /**
   * Get rowIndex
   * @return rowIndex
  **/
  @ApiModelProperty(value = "")
  public String getRowIndex() {
    return rowIndex;
  }

  public void setRowIndex(String rowIndex) {
    this.rowIndex = rowIndex;
  }

  public Section sectionRows(String sectionRows) {
    this.sectionRows = sectionRows;
    return this;
  }

   /**
   * Get sectionRows
   * @return sectionRows
  **/
  @ApiModelProperty(value = "")
  public String getSectionRows() {
    return sectionRows;
  }

  public void setSectionRows(String sectionRows) {
    this.sectionRows = sectionRows;
  }

  public Section name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Section columnSpan(String columnSpan) {
    this.columnSpan = columnSpan;
    return this;
  }

   /**
   * Get columnSpan
   * @return columnSpan
  **/
  @ApiModelProperty(value = "")
  public String getColumnSpan() {
    return columnSpan;
  }

  public void setColumnSpan(String columnSpan) {
    this.columnSpan = columnSpan;
  }

  public Section sectionColumns(String sectionColumns) {
    this.sectionColumns = sectionColumns;
    return this;
  }

   /**
   * Get sectionColumns
   * @return sectionColumns
  **/
  @ApiModelProperty(value = "")
  public String getSectionColumns() {
    return sectionColumns;
  }

  public void setSectionColumns(String sectionColumns) {
    this.sectionColumns = sectionColumns;
  }

  public Section columnIndex(String columnIndex) {
    this.columnIndex = columnIndex;
    return this;
  }

   /**
   * Get columnIndex
   * @return columnIndex
  **/
  @ApiModelProperty(value = "")
  public String getColumnIndex() {
    return columnIndex;
  }

  public void setColumnIndex(String columnIndex) {
    this.columnIndex = columnIndex;
  }

  public Section rowSpan(String rowSpan) {
    this.rowSpan = rowSpan;
    return this;
  }

   /**
   * Get rowSpan
   * @return rowSpan
  **/
  @ApiModelProperty(value = "")
  public String getRowSpan() {
    return rowSpan;
  }

  public void setRowSpan(String rowSpan) {
    this.rowSpan = rowSpan;
  }

  public Section removed(Boolean removed) {
    this.removed = removed;
    return this;
  }

   /**
   * Get removed
   * @return removed
  **/
  @ApiModelProperty(value = "")
  public Boolean isRemoved() {
    return removed;
  }

  public void setRemoved(Boolean removed) {
    this.removed = removed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Section section = (Section) o;
    return Objects.equals(this.subsections, section.subsections) &&
        Objects.equals(this.displayName, section.displayName) &&
        Objects.equals(this.rowIndex, section.rowIndex) &&
        Objects.equals(this.sectionRows, section.sectionRows) &&
        Objects.equals(this.name, section.name) &&
        Objects.equals(this.columnSpan, section.columnSpan) &&
        Objects.equals(this.sectionColumns, section.sectionColumns) &&
        Objects.equals(this.columnIndex, section.columnIndex) &&
        Objects.equals(this.rowSpan, section.rowSpan) &&
        Objects.equals(this.removed, section.removed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subsections, displayName, rowIndex, sectionRows, name, columnSpan, sectionColumns, columnIndex, rowSpan, removed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Section {\n");
    
    sb.append("    subsections: ").append(toIndentedString(subsections)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    rowIndex: ").append(toIndentedString(rowIndex)).append("\n");
    sb.append("    sectionRows: ").append(toIndentedString(sectionRows)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    columnSpan: ").append(toIndentedString(columnSpan)).append("\n");
    sb.append("    sectionColumns: ").append(toIndentedString(sectionColumns)).append("\n");
    sb.append("    columnIndex: ").append(toIndentedString(columnIndex)).append("\n");
    sb.append("    rowSpan: ").append(toIndentedString(rowSpan)).append("\n");
    sb.append("    removed: ").append(toIndentedString(removed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

