/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * StackEntity
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class StackEntity {
  @SerializedName("stackId")
  private Long stackId = null;

  @SerializedName("stackName")
  private String stackName = null;

  @SerializedName("stackVersion")
  private String stackVersion = null;

  public StackEntity stackId(Long stackId) {
    this.stackId = stackId;
    return this;
  }

   /**
   * Get stackId
   * @return stackId
  **/
  @ApiModelProperty(value = "")
  public Long getStackId() {
    return stackId;
  }

  public void setStackId(Long stackId) {
    this.stackId = stackId;
  }

  public StackEntity stackName(String stackName) {
    this.stackName = stackName;
    return this;
  }

   /**
   * Get stackName
   * @return stackName
  **/
  @ApiModelProperty(value = "")
  public String getStackName() {
    return stackName;
  }

  public void setStackName(String stackName) {
    this.stackName = stackName;
  }

  public StackEntity stackVersion(String stackVersion) {
    this.stackVersion = stackVersion;
    return this;
  }

   /**
   * Get stackVersion
   * @return stackVersion
  **/
  @ApiModelProperty(value = "")
  public String getStackVersion() {
    return stackVersion;
  }

  public void setStackVersion(String stackVersion) {
    this.stackVersion = stackVersion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StackEntity stackEntity = (StackEntity) o;
    return Objects.equals(this.stackId, stackEntity.stackId) &&
        Objects.equals(this.stackName, stackEntity.stackName) &&
        Objects.equals(this.stackVersion, stackEntity.stackVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stackId, stackName, stackVersion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StackEntity {\n");
    
    sb.append("    stackId: ").append(toIndentedString(stackId)).append("\n");
    sb.append("    stackName: ").append(toIndentedString(stackName)).append("\n");
    sb.append("    stackVersion: ").append(toIndentedString(stackVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

