/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import sunbox.sdp.ambari.client.model.Section;

/**
 * TabLayout
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class TabLayout {
  @SerializedName("tab-rows")
  private String tabRows = null;

  @SerializedName("sections")
  private List<Section> sections = null;

  @SerializedName("tab-columns")
  private String tabColumns = null;

  public TabLayout tabRows(String tabRows) {
    this.tabRows = tabRows;
    return this;
  }

   /**
   * Get tabRows
   * @return tabRows
  **/
  @ApiModelProperty(value = "")
  public String getTabRows() {
    return tabRows;
  }

  public void setTabRows(String tabRows) {
    this.tabRows = tabRows;
  }

  public TabLayout sections(List<Section> sections) {
    this.sections = sections;
    return this;
  }

  public TabLayout addSectionsItem(Section sectionsItem) {
    if (this.sections == null) {
      this.sections = new ArrayList<Section>();
    }
    this.sections.add(sectionsItem);
    return this;
  }

   /**
   * Get sections
   * @return sections
  **/
  @ApiModelProperty(value = "")
  public List<Section> getSections() {
    return sections;
  }

  public void setSections(List<Section> sections) {
    this.sections = sections;
  }

  public TabLayout tabColumns(String tabColumns) {
    this.tabColumns = tabColumns;
    return this;
  }

   /**
   * Get tabColumns
   * @return tabColumns
  **/
  @ApiModelProperty(value = "")
  public String getTabColumns() {
    return tabColumns;
  }

  public void setTabColumns(String tabColumns) {
    this.tabColumns = tabColumns;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TabLayout tabLayout = (TabLayout) o;
    return Objects.equals(this.tabRows, tabLayout.tabRows) &&
        Objects.equals(this.sections, tabLayout.sections) &&
        Objects.equals(this.tabColumns, tabLayout.tabColumns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tabRows, sections, tabColumns);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TabLayout {\n");
    
    sb.append("    tabRows: ").append(toIndentedString(tabRows)).append("\n");
    sb.append("    sections: ").append(toIndentedString(sections)).append("\n");
    sb.append("    tabColumns: ").append(toIndentedString(tabColumns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

