/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UserAuthenticationSourceRequestUpdateInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class UserAuthenticationSourceRequestUpdateInfo {
  @SerializedName("key")
  private String key = null;

  @SerializedName("old_key")
  private String oldKey = null;

  public UserAuthenticationSourceRequestUpdateInfo key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @ApiModelProperty(required = true, value = "")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public UserAuthenticationSourceRequestUpdateInfo oldKey(String oldKey) {
    this.oldKey = oldKey;
    return this;
  }

   /**
   * Get oldKey
   * @return oldKey
  **/
  @ApiModelProperty(value = "")
  public String getOldKey() {
    return oldKey;
  }

  public void setOldKey(String oldKey) {
    this.oldKey = oldKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserAuthenticationSourceRequestUpdateInfo userAuthenticationSourceRequestUpdateInfo = (UserAuthenticationSourceRequestUpdateInfo) o;
    return Objects.equals(this.key, userAuthenticationSourceRequestUpdateInfo.key) &&
        Objects.equals(this.oldKey, userAuthenticationSourceRequestUpdateInfo.oldKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, oldKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserAuthenticationSourceRequestUpdateInfo {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    oldKey: ").append(toIndentedString(oldKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

