/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import sunbox.sdp.ambari.client.model.UserGroupInfo;
import sunbox.sdp.ambari.client.model.ValueEntryInfo;

/**
 * ValueAttributesInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class ValueAttributesInfo {
  @SerializedName("type")
  private String type = null;

  @SerializedName("maximum")
  private String maximum = null;

  @SerializedName("minimum")
  private String minimum = null;

  @SerializedName("unit")
  private String unit = null;

  @SerializedName("delete")
  private String delete = null;

  @SerializedName("visible")
  private Boolean visible = false;

  @SerializedName("overridable")
  private Boolean overridable = false;

  @SerializedName("copy")
  private String copy = null;

  @SerializedName("empty_value_valid")
  private Boolean emptyValueValid = false;

  @SerializedName("ui_only_property")
  private Boolean uiOnlyProperty = false;

  @SerializedName("read_only")
  private Boolean readOnly = false;

  @SerializedName("editable_only_at_install")
  private Boolean editableOnlyAtInstall = false;

  @SerializedName("show_property_name")
  private Boolean showPropertyName = false;

  @SerializedName("increment_step")
  private String incrementStep = null;

  @SerializedName("entries")
  private List<ValueEntryInfo> entries = null;

  @SerializedName("hidden")
  private String hidden = null;

  @SerializedName("entries_editable")
  private Boolean entriesEditable = false;

  @SerializedName("selection_cardinality")
  private String selectionCardinality = null;

  @SerializedName("property-file-name")
  private String propertyFileName = null;

  @SerializedName("property-file-type")
  private String propertyFileType = null;

  @SerializedName("user-group-entries")
  private List<UserGroupInfo> userGroupEntries = null;

  @SerializedName("keystore")
  private Boolean keystore = false;

  public ValueAttributesInfo type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ValueAttributesInfo maximum(String maximum) {
    this.maximum = maximum;
    return this;
  }

   /**
   * Get maximum
   * @return maximum
  **/
  @ApiModelProperty(value = "")
  public String getMaximum() {
    return maximum;
  }

  public void setMaximum(String maximum) {
    this.maximum = maximum;
  }

  public ValueAttributesInfo minimum(String minimum) {
    this.minimum = minimum;
    return this;
  }

   /**
   * Get minimum
   * @return minimum
  **/
  @ApiModelProperty(value = "")
  public String getMinimum() {
    return minimum;
  }

  public void setMinimum(String minimum) {
    this.minimum = minimum;
  }

  public ValueAttributesInfo unit(String unit) {
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @ApiModelProperty(value = "")
  public String getUnit() {
    return unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }

  public ValueAttributesInfo delete(String delete) {
    this.delete = delete;
    return this;
  }

   /**
   * Get delete
   * @return delete
  **/
  @ApiModelProperty(value = "")
  public String getDelete() {
    return delete;
  }

  public void setDelete(String delete) {
    this.delete = delete;
  }

  public ValueAttributesInfo visible(Boolean visible) {
    this.visible = visible;
    return this;
  }

   /**
   * Get visible
   * @return visible
  **/
  @ApiModelProperty(value = "")
  public Boolean isVisible() {
    return visible;
  }

  public void setVisible(Boolean visible) {
    this.visible = visible;
  }

  public ValueAttributesInfo overridable(Boolean overridable) {
    this.overridable = overridable;
    return this;
  }

   /**
   * Get overridable
   * @return overridable
  **/
  @ApiModelProperty(value = "")
  public Boolean isOverridable() {
    return overridable;
  }

  public void setOverridable(Boolean overridable) {
    this.overridable = overridable;
  }

  public ValueAttributesInfo copy(String copy) {
    this.copy = copy;
    return this;
  }

   /**
   * Get copy
   * @return copy
  **/
  @ApiModelProperty(value = "")
  public String getCopy() {
    return copy;
  }

  public void setCopy(String copy) {
    this.copy = copy;
  }

  public ValueAttributesInfo emptyValueValid(Boolean emptyValueValid) {
    this.emptyValueValid = emptyValueValid;
    return this;
  }

   /**
   * Get emptyValueValid
   * @return emptyValueValid
  **/
  @ApiModelProperty(value = "")
  public Boolean isEmptyValueValid() {
    return emptyValueValid;
  }

  public void setEmptyValueValid(Boolean emptyValueValid) {
    this.emptyValueValid = emptyValueValid;
  }

  public ValueAttributesInfo uiOnlyProperty(Boolean uiOnlyProperty) {
    this.uiOnlyProperty = uiOnlyProperty;
    return this;
  }

   /**
   * Get uiOnlyProperty
   * @return uiOnlyProperty
  **/
  @ApiModelProperty(value = "")
  public Boolean isUiOnlyProperty() {
    return uiOnlyProperty;
  }

  public void setUiOnlyProperty(Boolean uiOnlyProperty) {
    this.uiOnlyProperty = uiOnlyProperty;
  }

  public ValueAttributesInfo readOnly(Boolean readOnly) {
    this.readOnly = readOnly;
    return this;
  }

   /**
   * Get readOnly
   * @return readOnly
  **/
  @ApiModelProperty(value = "")
  public Boolean isReadOnly() {
    return readOnly;
  }

  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }

  public ValueAttributesInfo editableOnlyAtInstall(Boolean editableOnlyAtInstall) {
    this.editableOnlyAtInstall = editableOnlyAtInstall;
    return this;
  }

   /**
   * Get editableOnlyAtInstall
   * @return editableOnlyAtInstall
  **/
  @ApiModelProperty(value = "")
  public Boolean isEditableOnlyAtInstall() {
    return editableOnlyAtInstall;
  }

  public void setEditableOnlyAtInstall(Boolean editableOnlyAtInstall) {
    this.editableOnlyAtInstall = editableOnlyAtInstall;
  }

  public ValueAttributesInfo showPropertyName(Boolean showPropertyName) {
    this.showPropertyName = showPropertyName;
    return this;
  }

   /**
   * Get showPropertyName
   * @return showPropertyName
  **/
  @ApiModelProperty(value = "")
  public Boolean isShowPropertyName() {
    return showPropertyName;
  }

  public void setShowPropertyName(Boolean showPropertyName) {
    this.showPropertyName = showPropertyName;
  }

  public ValueAttributesInfo incrementStep(String incrementStep) {
    this.incrementStep = incrementStep;
    return this;
  }

   /**
   * Get incrementStep
   * @return incrementStep
  **/
  @ApiModelProperty(value = "")
  public String getIncrementStep() {
    return incrementStep;
  }

  public void setIncrementStep(String incrementStep) {
    this.incrementStep = incrementStep;
  }

  public ValueAttributesInfo entries(List<ValueEntryInfo> entries) {
    this.entries = entries;
    return this;
  }

  public ValueAttributesInfo addEntriesItem(ValueEntryInfo entriesItem) {
    if (this.entries == null) {
      this.entries = new ArrayList<ValueEntryInfo>();
    }
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  @ApiModelProperty(value = "")
  public List<ValueEntryInfo> getEntries() {
    return entries;
  }

  public void setEntries(List<ValueEntryInfo> entries) {
    this.entries = entries;
  }

  public ValueAttributesInfo hidden(String hidden) {
    this.hidden = hidden;
    return this;
  }

   /**
   * Get hidden
   * @return hidden
  **/
  @ApiModelProperty(value = "")
  public String getHidden() {
    return hidden;
  }

  public void setHidden(String hidden) {
    this.hidden = hidden;
  }

  public ValueAttributesInfo entriesEditable(Boolean entriesEditable) {
    this.entriesEditable = entriesEditable;
    return this;
  }

   /**
   * Get entriesEditable
   * @return entriesEditable
  **/
  @ApiModelProperty(value = "")
  public Boolean isEntriesEditable() {
    return entriesEditable;
  }

  public void setEntriesEditable(Boolean entriesEditable) {
    this.entriesEditable = entriesEditable;
  }

  public ValueAttributesInfo selectionCardinality(String selectionCardinality) {
    this.selectionCardinality = selectionCardinality;
    return this;
  }

   /**
   * Get selectionCardinality
   * @return selectionCardinality
  **/
  @ApiModelProperty(value = "")
  public String getSelectionCardinality() {
    return selectionCardinality;
  }

  public void setSelectionCardinality(String selectionCardinality) {
    this.selectionCardinality = selectionCardinality;
  }

  public ValueAttributesInfo propertyFileName(String propertyFileName) {
    this.propertyFileName = propertyFileName;
    return this;
  }

   /**
   * Get propertyFileName
   * @return propertyFileName
  **/
  @ApiModelProperty(value = "")
  public String getPropertyFileName() {
    return propertyFileName;
  }

  public void setPropertyFileName(String propertyFileName) {
    this.propertyFileName = propertyFileName;
  }

  public ValueAttributesInfo propertyFileType(String propertyFileType) {
    this.propertyFileType = propertyFileType;
    return this;
  }

   /**
   * Get propertyFileType
   * @return propertyFileType
  **/
  @ApiModelProperty(value = "")
  public String getPropertyFileType() {
    return propertyFileType;
  }

  public void setPropertyFileType(String propertyFileType) {
    this.propertyFileType = propertyFileType;
  }

  public ValueAttributesInfo userGroupEntries(List<UserGroupInfo> userGroupEntries) {
    this.userGroupEntries = userGroupEntries;
    return this;
  }

  public ValueAttributesInfo addUserGroupEntriesItem(UserGroupInfo userGroupEntriesItem) {
    if (this.userGroupEntries == null) {
      this.userGroupEntries = new ArrayList<UserGroupInfo>();
    }
    this.userGroupEntries.add(userGroupEntriesItem);
    return this;
  }

   /**
   * Get userGroupEntries
   * @return userGroupEntries
  **/
  @ApiModelProperty(value = "")
  public List<UserGroupInfo> getUserGroupEntries() {
    return userGroupEntries;
  }

  public void setUserGroupEntries(List<UserGroupInfo> userGroupEntries) {
    this.userGroupEntries = userGroupEntries;
  }

  public ValueAttributesInfo keystore(Boolean keystore) {
    this.keystore = keystore;
    return this;
  }

   /**
   * Get keystore
   * @return keystore
  **/
  @ApiModelProperty(value = "")
  public Boolean isKeystore() {
    return keystore;
  }

  public void setKeystore(Boolean keystore) {
    this.keystore = keystore;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValueAttributesInfo valueAttributesInfo = (ValueAttributesInfo) o;
    return Objects.equals(this.type, valueAttributesInfo.type) &&
        Objects.equals(this.maximum, valueAttributesInfo.maximum) &&
        Objects.equals(this.minimum, valueAttributesInfo.minimum) &&
        Objects.equals(this.unit, valueAttributesInfo.unit) &&
        Objects.equals(this.delete, valueAttributesInfo.delete) &&
        Objects.equals(this.visible, valueAttributesInfo.visible) &&
        Objects.equals(this.overridable, valueAttributesInfo.overridable) &&
        Objects.equals(this.copy, valueAttributesInfo.copy) &&
        Objects.equals(this.emptyValueValid, valueAttributesInfo.emptyValueValid) &&
        Objects.equals(this.uiOnlyProperty, valueAttributesInfo.uiOnlyProperty) &&
        Objects.equals(this.readOnly, valueAttributesInfo.readOnly) &&
        Objects.equals(this.editableOnlyAtInstall, valueAttributesInfo.editableOnlyAtInstall) &&
        Objects.equals(this.showPropertyName, valueAttributesInfo.showPropertyName) &&
        Objects.equals(this.incrementStep, valueAttributesInfo.incrementStep) &&
        Objects.equals(this.entries, valueAttributesInfo.entries) &&
        Objects.equals(this.hidden, valueAttributesInfo.hidden) &&
        Objects.equals(this.entriesEditable, valueAttributesInfo.entriesEditable) &&
        Objects.equals(this.selectionCardinality, valueAttributesInfo.selectionCardinality) &&
        Objects.equals(this.propertyFileName, valueAttributesInfo.propertyFileName) &&
        Objects.equals(this.propertyFileType, valueAttributesInfo.propertyFileType) &&
        Objects.equals(this.userGroupEntries, valueAttributesInfo.userGroupEntries) &&
        Objects.equals(this.keystore, valueAttributesInfo.keystore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, maximum, minimum, unit, delete, visible, overridable, copy, emptyValueValid, uiOnlyProperty, readOnly, editableOnlyAtInstall, showPropertyName, incrementStep, entries, hidden, entriesEditable, selectionCardinality, propertyFileName, propertyFileType, userGroupEntries, keystore);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValueAttributesInfo {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    maximum: ").append(toIndentedString(maximum)).append("\n");
    sb.append("    minimum: ").append(toIndentedString(minimum)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    delete: ").append(toIndentedString(delete)).append("\n");
    sb.append("    visible: ").append(toIndentedString(visible)).append("\n");
    sb.append("    overridable: ").append(toIndentedString(overridable)).append("\n");
    sb.append("    copy: ").append(toIndentedString(copy)).append("\n");
    sb.append("    emptyValueValid: ").append(toIndentedString(emptyValueValid)).append("\n");
    sb.append("    uiOnlyProperty: ").append(toIndentedString(uiOnlyProperty)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    editableOnlyAtInstall: ").append(toIndentedString(editableOnlyAtInstall)).append("\n");
    sb.append("    showPropertyName: ").append(toIndentedString(showPropertyName)).append("\n");
    sb.append("    incrementStep: ").append(toIndentedString(incrementStep)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("    entriesEditable: ").append(toIndentedString(entriesEditable)).append("\n");
    sb.append("    selectionCardinality: ").append(toIndentedString(selectionCardinality)).append("\n");
    sb.append("    propertyFileName: ").append(toIndentedString(propertyFileName)).append("\n");
    sb.append("    propertyFileType: ").append(toIndentedString(propertyFileType)).append("\n");
    sb.append("    userGroupEntries: ").append(toIndentedString(userGroupEntries)).append("\n");
    sb.append("    keystore: ").append(toIndentedString(keystore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

