/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import sunbox.sdp.ambari.client.model.ViewInstanceResponseInfo;

/**
 * ViewInstanceResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class ViewInstanceResponse {
  @SerializedName("ViewInstanceInfo")
  private ViewInstanceResponseInfo viewInstanceInfo = null;

  public ViewInstanceResponse viewInstanceInfo(ViewInstanceResponseInfo viewInstanceInfo) {
    this.viewInstanceInfo = viewInstanceInfo;
    return this;
  }

   /**
   * Get viewInstanceInfo
   * @return viewInstanceInfo
  **/
  @ApiModelProperty(value = "")
  public ViewInstanceResponseInfo getViewInstanceInfo() {
    return viewInstanceInfo;
  }

  public void setViewInstanceInfo(ViewInstanceResponseInfo viewInstanceInfo) {
    this.viewInstanceInfo = viewInstanceInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ViewInstanceResponse viewInstanceResponse = (ViewInstanceResponse) o;
    return Objects.equals(this.viewInstanceInfo, viewInstanceResponse.viewInstanceInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(viewInstanceInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ViewInstanceResponse {\n");
    
    sb.append("    viewInstanceInfo: ").append(toIndentedString(viewInstanceInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

