/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ViewUrlInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class ViewUrlInfo {
  @SerializedName("view_instance_name")
  private String viewInstanceName = null;

  @SerializedName("url_name")
  private String urlName = null;

  @SerializedName("url_suffix")
  private String urlSuffix = null;

  @SerializedName("view_instance_common_name")
  private String viewInstanceCommonName = null;

  @SerializedName("view_instance_version")
  private String viewInstanceVersion = null;

  public ViewUrlInfo viewInstanceName(String viewInstanceName) {
    this.viewInstanceName = viewInstanceName;
    return this;
  }

   /**
   * Get viewInstanceName
   * @return viewInstanceName
  **/
  @ApiModelProperty(value = "")
  public String getViewInstanceName() {
    return viewInstanceName;
  }

  public void setViewInstanceName(String viewInstanceName) {
    this.viewInstanceName = viewInstanceName;
  }

  public ViewUrlInfo urlName(String urlName) {
    this.urlName = urlName;
    return this;
  }

   /**
   * Get urlName
   * @return urlName
  **/
  @ApiModelProperty(value = "")
  public String getUrlName() {
    return urlName;
  }

  public void setUrlName(String urlName) {
    this.urlName = urlName;
  }

  public ViewUrlInfo urlSuffix(String urlSuffix) {
    this.urlSuffix = urlSuffix;
    return this;
  }

   /**
   * Get urlSuffix
   * @return urlSuffix
  **/
  @ApiModelProperty(value = "")
  public String getUrlSuffix() {
    return urlSuffix;
  }

  public void setUrlSuffix(String urlSuffix) {
    this.urlSuffix = urlSuffix;
  }

  public ViewUrlInfo viewInstanceCommonName(String viewInstanceCommonName) {
    this.viewInstanceCommonName = viewInstanceCommonName;
    return this;
  }

   /**
   * Get viewInstanceCommonName
   * @return viewInstanceCommonName
  **/
  @ApiModelProperty(value = "")
  public String getViewInstanceCommonName() {
    return viewInstanceCommonName;
  }

  public void setViewInstanceCommonName(String viewInstanceCommonName) {
    this.viewInstanceCommonName = viewInstanceCommonName;
  }

  public ViewUrlInfo viewInstanceVersion(String viewInstanceVersion) {
    this.viewInstanceVersion = viewInstanceVersion;
    return this;
  }

   /**
   * Get viewInstanceVersion
   * @return viewInstanceVersion
  **/
  @ApiModelProperty(value = "")
  public String getViewInstanceVersion() {
    return viewInstanceVersion;
  }

  public void setViewInstanceVersion(String viewInstanceVersion) {
    this.viewInstanceVersion = viewInstanceVersion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ViewUrlInfo viewUrlInfo = (ViewUrlInfo) o;
    return Objects.equals(this.viewInstanceName, viewUrlInfo.viewInstanceName) &&
        Objects.equals(this.urlName, viewUrlInfo.urlName) &&
        Objects.equals(this.urlSuffix, viewUrlInfo.urlSuffix) &&
        Objects.equals(this.viewInstanceCommonName, viewUrlInfo.viewInstanceCommonName) &&
        Objects.equals(this.viewInstanceVersion, viewUrlInfo.viewInstanceVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(viewInstanceName, urlName, urlSuffix, viewInstanceCommonName, viewInstanceVersion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ViewUrlInfo {\n");
    
    sb.append("    viewInstanceName: ").append(toIndentedString(viewInstanceName)).append("\n");
    sb.append("    urlName: ").append(toIndentedString(urlName)).append("\n");
    sb.append("    urlSuffix: ").append(toIndentedString(urlSuffix)).append("\n");
    sb.append("    viewInstanceCommonName: ").append(toIndentedString(viewInstanceCommonName)).append("\n");
    sb.append("    viewInstanceVersion: ").append(toIndentedString(viewInstanceVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

