/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * WidgetResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-11-26T12:16:58.440+08:00")
public class WidgetResponse {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("widgetName")
  private String widgetName = null;

  @SerializedName("widgetType")
  private String widgetType = null;

  @SerializedName("metrics")
  private String metrics = null;

  @SerializedName("timeCreated")
  private Long timeCreated = null;

  @SerializedName("author")
  private String author = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("scope")
  private String scope = null;

  @SerializedName("widgetValues")
  private String widgetValues = null;

  @SerializedName("properties")
  private String properties = null;

  @SerializedName("clusterName")
  private String clusterName = null;

  @SerializedName("tag")
  private String tag = null;

  public WidgetResponse id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public WidgetResponse widgetName(String widgetName) {
    this.widgetName = widgetName;
    return this;
  }

   /**
   * Get widgetName
   * @return widgetName
  **/
  @ApiModelProperty(value = "")
  public String getWidgetName() {
    return widgetName;
  }

  public void setWidgetName(String widgetName) {
    this.widgetName = widgetName;
  }

  public WidgetResponse widgetType(String widgetType) {
    this.widgetType = widgetType;
    return this;
  }

   /**
   * Get widgetType
   * @return widgetType
  **/
  @ApiModelProperty(value = "")
  public String getWidgetType() {
    return widgetType;
  }

  public void setWidgetType(String widgetType) {
    this.widgetType = widgetType;
  }

  public WidgetResponse metrics(String metrics) {
    this.metrics = metrics;
    return this;
  }

   /**
   * Get metrics
   * @return metrics
  **/
  @ApiModelProperty(value = "")
  public String getMetrics() {
    return metrics;
  }

  public void setMetrics(String metrics) {
    this.metrics = metrics;
  }

  public WidgetResponse timeCreated(Long timeCreated) {
    this.timeCreated = timeCreated;
    return this;
  }

   /**
   * Get timeCreated
   * @return timeCreated
  **/
  @ApiModelProperty(value = "")
  public Long getTimeCreated() {
    return timeCreated;
  }

  public void setTimeCreated(Long timeCreated) {
    this.timeCreated = timeCreated;
  }

  public WidgetResponse author(String author) {
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @ApiModelProperty(value = "")
  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public WidgetResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public WidgetResponse displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public WidgetResponse scope(String scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  @ApiModelProperty(value = "")
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }

  public WidgetResponse widgetValues(String widgetValues) {
    this.widgetValues = widgetValues;
    return this;
  }

   /**
   * Get widgetValues
   * @return widgetValues
  **/
  @ApiModelProperty(value = "")
  public String getWidgetValues() {
    return widgetValues;
  }

  public void setWidgetValues(String widgetValues) {
    this.widgetValues = widgetValues;
  }

  public WidgetResponse properties(String properties) {
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @ApiModelProperty(value = "")
  public String getProperties() {
    return properties;
  }

  public void setProperties(String properties) {
    this.properties = properties;
  }

  public WidgetResponse clusterName(String clusterName) {
    this.clusterName = clusterName;
    return this;
  }

   /**
   * Get clusterName
   * @return clusterName
  **/
  @ApiModelProperty(value = "")
  public String getClusterName() {
    return clusterName;
  }

  public void setClusterName(String clusterName) {
    this.clusterName = clusterName;
  }

  public WidgetResponse tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  @ApiModelProperty(value = "")
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WidgetResponse widgetResponse = (WidgetResponse) o;
    return Objects.equals(this.id, widgetResponse.id) &&
        Objects.equals(this.widgetName, widgetResponse.widgetName) &&
        Objects.equals(this.widgetType, widgetResponse.widgetType) &&
        Objects.equals(this.metrics, widgetResponse.metrics) &&
        Objects.equals(this.timeCreated, widgetResponse.timeCreated) &&
        Objects.equals(this.author, widgetResponse.author) &&
        Objects.equals(this.description, widgetResponse.description) &&
        Objects.equals(this.displayName, widgetResponse.displayName) &&
        Objects.equals(this.scope, widgetResponse.scope) &&
        Objects.equals(this.widgetValues, widgetResponse.widgetValues) &&
        Objects.equals(this.properties, widgetResponse.properties) &&
        Objects.equals(this.clusterName, widgetResponse.clusterName) &&
        Objects.equals(this.tag, widgetResponse.tag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, widgetName, widgetType, metrics, timeCreated, author, description, displayName, scope, widgetValues, properties, clusterName, tag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WidgetResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    widgetName: ").append(toIndentedString(widgetName)).append("\n");
    sb.append("    widgetType: ").append(toIndentedString(widgetType)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    timeCreated: ").append(toIndentedString(timeCreated)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    widgetValues: ").append(toIndentedString(widgetValues)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    clusterName: ").append(toIndentedString(clusterName)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

