/*
 * Swagger spec for Ambari REST API
 * Ambari REST APIs has inherent support for querying, sorting and pagination
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sunbox.sdp.ambari.client.api;

import sunbox.sdp.ambari.client.ApiCallback;
import sunbox.sdp.ambari.client.ApiClient;
import sunbox.sdp.ambari.client.ApiException;
import sunbox.sdp.ambari.client.ApiResponse;
import sunbox.sdp.ambari.client.Configuration;
import sunbox.sdp.ambari.client.Pair;
import sunbox.sdp.ambari.client.ProgressRequestBody;
import sunbox.sdp.ambari.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import sunbox.sdp.ambari.client.model.*;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ServicesApi {
    private ApiClient apiClient;

    public ServicesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ServicesApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for getRootHost
     * @param hostName host name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to Hosts/*)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getRootHostCall(String hostName, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/services/{serviceName}/hosts/{hostName}"
            .replaceAll("\\{" + "hostName" + "\\}", apiClient.escapeString(hostName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (fields != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("fields", fields));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/plain"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getRootHostValidateBeforeCall(String hostName, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'hostName' is set
        if (hostName == null) {
            throw new ApiException("Missing the required parameter 'hostName' when calling getRootHost(Async)");
        }
        

        com.squareup.okhttp.Call call = getRootHostCall(hostName, fields, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Returns information about the given host
     * 
     * @param hostName host name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to Hosts/*)
     * @return HostResponseWrapper
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public HostResponseWrapper getRootHost(String hostName, String fields) throws ApiException {
        ApiResponse<HostResponseWrapper> resp = getRootHostWithHttpInfo(hostName, fields);
        return resp.getData();
    }

    /**
     * Returns information about the given host
     * 
     * @param hostName host name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to Hosts/*)
     * @return ApiResponse&lt;HostResponseWrapper&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<HostResponseWrapper> getRootHostWithHttpInfo(String hostName, String fields) throws ApiException {
        com.squareup.okhttp.Call call = getRootHostValidateBeforeCall(hostName, fields, null, null);
        Type localVarReturnType = new TypeToken<HostResponseWrapper>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Returns information about the given host (asynchronously)
     * 
     * @param hostName host name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to Hosts/*)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getRootHostAsync(String hostName, String fields, final ApiCallback<HostResponseWrapper> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getRootHostValidateBeforeCall(hostName, fields, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<HostResponseWrapper>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getRootHosts
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to Hosts/host_name)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getRootHostsCall(String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/services/{serviceName}/hosts";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (fields != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("fields", fields));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/plain"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getRootHostsValidateBeforeCall(String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        

        com.squareup.okhttp.Call call = getRootHostsCall(fields, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Returns the list of hosts for the given root-level service
     * 
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to Hosts/host_name)
     * @return List&lt;HostResponseWrapper&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<HostResponseWrapper> getRootHosts(String fields) throws ApiException {
        ApiResponse<List<HostResponseWrapper>> resp = getRootHostsWithHttpInfo(fields);
        return resp.getData();
    }

    /**
     * Returns the list of hosts for the given root-level service
     * 
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to Hosts/host_name)
     * @return ApiResponse&lt;List&lt;HostResponseWrapper&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<HostResponseWrapper>> getRootHostsWithHttpInfo(String fields) throws ApiException {
        com.squareup.okhttp.Call call = getRootHostsValidateBeforeCall(fields, null, null);
        Type localVarReturnType = new TypeToken<List<HostResponseWrapper>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Returns the list of hosts for the given root-level service (asynchronously)
     * 
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to Hosts/host_name)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getRootHostsAsync(String fields, final ApiCallback<List<HostResponseWrapper>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getRootHostsValidateBeforeCall(fields, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<HostResponseWrapper>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getRootService
     * @param serviceName service name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootService/service_name, components/RootServiceComponents/component_name, components/RootServiceComponents/service_name)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getRootServiceCall(String serviceName, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/services/{serviceName}"
            .replaceAll("\\{" + "serviceName" + "\\}", apiClient.escapeString(serviceName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (fields != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("fields", fields));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/plain"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getRootServiceValidateBeforeCall(String serviceName, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'serviceName' is set
        if (serviceName == null) {
            throw new ApiException("Missing the required parameter 'serviceName' when calling getRootService(Async)");
        }
        

        com.squareup.okhttp.Call call = getRootServiceCall(serviceName, fields, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Returns information about the given root-level service, including a list of its components
     * 
     * @param serviceName service name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootService/service_name, components/RootServiceComponents/component_name, components/RootServiceComponents/service_name)
     * @return RootServiceResponseWithComponentList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public RootServiceResponseWithComponentList getRootService(String serviceName, String fields) throws ApiException {
        ApiResponse<RootServiceResponseWithComponentList> resp = getRootServiceWithHttpInfo(serviceName, fields);
        return resp.getData();
    }

    /**
     * Returns information about the given root-level service, including a list of its components
     * 
     * @param serviceName service name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootService/service_name, components/RootServiceComponents/component_name, components/RootServiceComponents/service_name)
     * @return ApiResponse&lt;RootServiceResponseWithComponentList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<RootServiceResponseWithComponentList> getRootServiceWithHttpInfo(String serviceName, String fields) throws ApiException {
        com.squareup.okhttp.Call call = getRootServiceValidateBeforeCall(serviceName, fields, null, null);
        Type localVarReturnType = new TypeToken<RootServiceResponseWithComponentList>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Returns information about the given root-level service, including a list of its components (asynchronously)
     * 
     * @param serviceName service name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootService/service_name, components/RootServiceComponents/component_name, components/RootServiceComponents/service_name)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getRootServiceAsync(String serviceName, String fields, final ApiCallback<RootServiceResponseWithComponentList> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getRootServiceValidateBeforeCall(serviceName, fields, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<RootServiceResponseWithComponentList>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getRootServiceComponent
     * @param serviceName service name (required)
     * @param componentName component name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceComponents/*, hostComponents/RootServiceHostComponents/component_name, hostComponents/RootServiceHostComponents/host_name, hostComponents/RootServiceHostComponents/service_name)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getRootServiceComponentCall(String serviceName, String componentName, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/services/{serviceName}/components/{componentName}"
            .replaceAll("\\{" + "serviceName" + "\\}", apiClient.escapeString(serviceName.toString()))
            .replaceAll("\\{" + "componentName" + "\\}", apiClient.escapeString(componentName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (fields != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("fields", fields));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/plain"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getRootServiceComponentValidateBeforeCall(String serviceName, String componentName, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'serviceName' is set
        if (serviceName == null) {
            throw new ApiException("Missing the required parameter 'serviceName' when calling getRootServiceComponent(Async)");
        }
        
        // verify the required parameter 'componentName' is set
        if (componentName == null) {
            throw new ApiException("Missing the required parameter 'componentName' when calling getRootServiceComponent(Async)");
        }
        

        com.squareup.okhttp.Call call = getRootServiceComponentCall(serviceName, componentName, fields, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Returns information about the given component for the given root-level service
     * 
     * @param serviceName service name (required)
     * @param componentName component name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceComponents/*, hostComponents/RootServiceHostComponents/component_name, hostComponents/RootServiceHostComponents/host_name, hostComponents/RootServiceHostComponents/service_name)
     * @return RootServiceComponentWithHostComponentList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public RootServiceComponentWithHostComponentList getRootServiceComponent(String serviceName, String componentName, String fields) throws ApiException {
        ApiResponse<RootServiceComponentWithHostComponentList> resp = getRootServiceComponentWithHttpInfo(serviceName, componentName, fields);
        return resp.getData();
    }

    /**
     * Returns information about the given component for the given root-level service
     * 
     * @param serviceName service name (required)
     * @param componentName component name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceComponents/*, hostComponents/RootServiceHostComponents/component_name, hostComponents/RootServiceHostComponents/host_name, hostComponents/RootServiceHostComponents/service_name)
     * @return ApiResponse&lt;RootServiceComponentWithHostComponentList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<RootServiceComponentWithHostComponentList> getRootServiceComponentWithHttpInfo(String serviceName, String componentName, String fields) throws ApiException {
        com.squareup.okhttp.Call call = getRootServiceComponentValidateBeforeCall(serviceName, componentName, fields, null, null);
        Type localVarReturnType = new TypeToken<RootServiceComponentWithHostComponentList>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Returns information about the given component for the given root-level service (asynchronously)
     * 
     * @param serviceName service name (required)
     * @param componentName component name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceComponents/*, hostComponents/RootServiceHostComponents/component_name, hostComponents/RootServiceHostComponents/host_name, hostComponents/RootServiceHostComponents/service_name)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getRootServiceComponentAsync(String serviceName, String componentName, String fields, final ApiCallback<RootServiceComponentWithHostComponentList> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getRootServiceComponentValidateBeforeCall(serviceName, componentName, fields, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<RootServiceComponentWithHostComponentList>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getRootServiceComponentHosts
     * @param serviceName service name (required)
     * @param componentName component name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceHostComponents/component_name, RootServiceHostComponents/host_name, RootServiceHostComponents/service_name)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getRootServiceComponentHostsCall(String serviceName, String componentName, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/services/{serviceName}/components/{componentName}/hostComponents"
            .replaceAll("\\{" + "serviceName" + "\\}", apiClient.escapeString(serviceName.toString()))
            .replaceAll("\\{" + "componentName" + "\\}", apiClient.escapeString(componentName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (fields != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("fields", fields));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/plain"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getRootServiceComponentHostsValidateBeforeCall(String serviceName, String componentName, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'serviceName' is set
        if (serviceName == null) {
            throw new ApiException("Missing the required parameter 'serviceName' when calling getRootServiceComponentHosts(Async)");
        }
        
        // verify the required parameter 'componentName' is set
        if (componentName == null) {
            throw new ApiException("Missing the required parameter 'componentName' when calling getRootServiceComponentHosts(Async)");
        }
        

        com.squareup.okhttp.Call call = getRootServiceComponentHostsCall(serviceName, componentName, fields, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Returns the list of hosts for the given root-level service component
     * 
     * @param serviceName service name (required)
     * @param componentName component name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceHostComponents/component_name, RootServiceHostComponents/host_name, RootServiceHostComponents/service_name)
     * @return List&lt;RootServiceHostComponentResponseWrapper&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<RootServiceHostComponentResponseWrapper> getRootServiceComponentHosts(String serviceName, String componentName, String fields) throws ApiException {
        ApiResponse<List<RootServiceHostComponentResponseWrapper>> resp = getRootServiceComponentHostsWithHttpInfo(serviceName, componentName, fields);
        return resp.getData();
    }

    /**
     * Returns the list of hosts for the given root-level service component
     * 
     * @param serviceName service name (required)
     * @param componentName component name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceHostComponents/component_name, RootServiceHostComponents/host_name, RootServiceHostComponents/service_name)
     * @return ApiResponse&lt;List&lt;RootServiceHostComponentResponseWrapper&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<RootServiceHostComponentResponseWrapper>> getRootServiceComponentHostsWithHttpInfo(String serviceName, String componentName, String fields) throws ApiException {
        com.squareup.okhttp.Call call = getRootServiceComponentHostsValidateBeforeCall(serviceName, componentName, fields, null, null);
        Type localVarReturnType = new TypeToken<List<RootServiceHostComponentResponseWrapper>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Returns the list of hosts for the given root-level service component (asynchronously)
     * 
     * @param serviceName service name (required)
     * @param componentName component name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceHostComponents/component_name, RootServiceHostComponents/host_name, RootServiceHostComponents/service_name)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getRootServiceComponentHostsAsync(String serviceName, String componentName, String fields, final ApiCallback<List<RootServiceHostComponentResponseWrapper>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getRootServiceComponentHostsValidateBeforeCall(serviceName, componentName, fields, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<RootServiceHostComponentResponseWrapper>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getRootServiceComponents
     * @param serviceName service name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceComponents/component_name, RootServiceComponents/service_name)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getRootServiceComponentsCall(String serviceName, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/services/{serviceName}/components"
            .replaceAll("\\{" + "serviceName" + "\\}", apiClient.escapeString(serviceName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (fields != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("fields", fields));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/plain"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getRootServiceComponentsValidateBeforeCall(String serviceName, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'serviceName' is set
        if (serviceName == null) {
            throw new ApiException("Missing the required parameter 'serviceName' when calling getRootServiceComponents(Async)");
        }
        

        com.squareup.okhttp.Call call = getRootServiceComponentsCall(serviceName, fields, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Returns the list of components for the given root-level service
     * 
     * @param serviceName service name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceComponents/component_name, RootServiceComponents/service_name)
     * @return List&lt;RootServiceComponentResponseWrapper&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<RootServiceComponentResponseWrapper> getRootServiceComponents(String serviceName, String fields) throws ApiException {
        ApiResponse<List<RootServiceComponentResponseWrapper>> resp = getRootServiceComponentsWithHttpInfo(serviceName, fields);
        return resp.getData();
    }

    /**
     * Returns the list of components for the given root-level service
     * 
     * @param serviceName service name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceComponents/component_name, RootServiceComponents/service_name)
     * @return ApiResponse&lt;List&lt;RootServiceComponentResponseWrapper&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<RootServiceComponentResponseWrapper>> getRootServiceComponentsWithHttpInfo(String serviceName, String fields) throws ApiException {
        com.squareup.okhttp.Call call = getRootServiceComponentsValidateBeforeCall(serviceName, fields, null, null);
        Type localVarReturnType = new TypeToken<List<RootServiceComponentResponseWrapper>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Returns the list of components for the given root-level service (asynchronously)
     * 
     * @param serviceName service name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceComponents/component_name, RootServiceComponents/service_name)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getRootServiceComponentsAsync(String serviceName, String fields, final ApiCallback<List<RootServiceComponentResponseWrapper>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getRootServiceComponentsValidateBeforeCall(serviceName, fields, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<RootServiceComponentResponseWrapper>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getRootServiceHostComponent
     * @param serviceName service name (required)
     * @param hostName host name (required)
     * @param hostComponent component name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceHostComponents/component_name, RootServiceHostComponents/host_name, RootServiceHostComponents/service_name)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getRootServiceHostComponentCall(String serviceName, String hostName, String hostComponent, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/services/{serviceName}/hosts/{hostName}/hostComponents/{hostComponent}"
            .replaceAll("\\{" + "serviceName" + "\\}", apiClient.escapeString(serviceName.toString()))
            .replaceAll("\\{" + "hostName" + "\\}", apiClient.escapeString(hostName.toString()))
            .replaceAll("\\{" + "hostComponent" + "\\}", apiClient.escapeString(hostComponent.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (fields != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("fields", fields));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/plain"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getRootServiceHostComponentValidateBeforeCall(String serviceName, String hostName, String hostComponent, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'serviceName' is set
        if (serviceName == null) {
            throw new ApiException("Missing the required parameter 'serviceName' when calling getRootServiceHostComponent(Async)");
        }
        
        // verify the required parameter 'hostName' is set
        if (hostName == null) {
            throw new ApiException("Missing the required parameter 'hostName' when calling getRootServiceHostComponent(Async)");
        }
        
        // verify the required parameter 'hostComponent' is set
        if (hostComponent == null) {
            throw new ApiException("Missing the required parameter 'hostComponent' when calling getRootServiceHostComponent(Async)");
        }
        

        com.squareup.okhttp.Call call = getRootServiceHostComponentCall(serviceName, hostName, hostComponent, fields, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Returns information about the given component for the given root-level service on the given host
     * 
     * @param serviceName service name (required)
     * @param hostName host name (required)
     * @param hostComponent component name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceHostComponents/component_name, RootServiceHostComponents/host_name, RootServiceHostComponents/service_name)
     * @return RootServiceHostComponentResponseWrapper
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public RootServiceHostComponentResponseWrapper getRootServiceHostComponent(String serviceName, String hostName, String hostComponent, String fields) throws ApiException {
        ApiResponse<RootServiceHostComponentResponseWrapper> resp = getRootServiceHostComponentWithHttpInfo(serviceName, hostName, hostComponent, fields);
        return resp.getData();
    }

    /**
     * Returns information about the given component for the given root-level service on the given host
     * 
     * @param serviceName service name (required)
     * @param hostName host name (required)
     * @param hostComponent component name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceHostComponents/component_name, RootServiceHostComponents/host_name, RootServiceHostComponents/service_name)
     * @return ApiResponse&lt;RootServiceHostComponentResponseWrapper&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<RootServiceHostComponentResponseWrapper> getRootServiceHostComponentWithHttpInfo(String serviceName, String hostName, String hostComponent, String fields) throws ApiException {
        com.squareup.okhttp.Call call = getRootServiceHostComponentValidateBeforeCall(serviceName, hostName, hostComponent, fields, null, null);
        Type localVarReturnType = new TypeToken<RootServiceHostComponentResponseWrapper>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Returns information about the given component for the given root-level service on the given host (asynchronously)
     * 
     * @param serviceName service name (required)
     * @param hostName host name (required)
     * @param hostComponent component name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceHostComponents/component_name, RootServiceHostComponents/host_name, RootServiceHostComponents/service_name)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getRootServiceHostComponentAsync(String serviceName, String hostName, String hostComponent, String fields, final ApiCallback<RootServiceHostComponentResponseWrapper> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getRootServiceHostComponentValidateBeforeCall(serviceName, hostName, hostComponent, fields, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<RootServiceHostComponentResponseWrapper>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getRootServiceHostComponents
     * @param serviceName service name (required)
     * @param hostName host name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceHostComponents/component_name, RootServiceHostComponents/host_name, RootServiceHostComponents/service_name)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getRootServiceHostComponentsCall(String serviceName, String hostName, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/services/{serviceName}/hosts/{hostName}/hostComponents"
            .replaceAll("\\{" + "serviceName" + "\\}", apiClient.escapeString(serviceName.toString()))
            .replaceAll("\\{" + "hostName" + "\\}", apiClient.escapeString(hostName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (fields != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("fields", fields));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/plain"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getRootServiceHostComponentsValidateBeforeCall(String serviceName, String hostName, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'serviceName' is set
        if (serviceName == null) {
            throw new ApiException("Missing the required parameter 'serviceName' when calling getRootServiceHostComponents(Async)");
        }
        
        // verify the required parameter 'hostName' is set
        if (hostName == null) {
            throw new ApiException("Missing the required parameter 'hostName' when calling getRootServiceHostComponents(Async)");
        }
        

        com.squareup.okhttp.Call call = getRootServiceHostComponentsCall(serviceName, hostName, fields, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Returns the list of components for the given root-level service on the given host
     * 
     * @param serviceName service name (required)
     * @param hostName host name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceHostComponents/component_name, RootServiceHostComponents/host_name, RootServiceHostComponents/service_name)
     * @return List&lt;RootServiceHostComponentResponseWrapper&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<RootServiceHostComponentResponseWrapper> getRootServiceHostComponents(String serviceName, String hostName, String fields) throws ApiException {
        ApiResponse<List<RootServiceHostComponentResponseWrapper>> resp = getRootServiceHostComponentsWithHttpInfo(serviceName, hostName, fields);
        return resp.getData();
    }

    /**
     * Returns the list of components for the given root-level service on the given host
     * 
     * @param serviceName service name (required)
     * @param hostName host name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceHostComponents/component_name, RootServiceHostComponents/host_name, RootServiceHostComponents/service_name)
     * @return ApiResponse&lt;List&lt;RootServiceHostComponentResponseWrapper&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<RootServiceHostComponentResponseWrapper>> getRootServiceHostComponentsWithHttpInfo(String serviceName, String hostName, String fields) throws ApiException {
        com.squareup.okhttp.Call call = getRootServiceHostComponentsValidateBeforeCall(serviceName, hostName, fields, null, null);
        Type localVarReturnType = new TypeToken<List<RootServiceHostComponentResponseWrapper>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Returns the list of components for the given root-level service on the given host (asynchronously)
     * 
     * @param serviceName service name (required)
     * @param hostName host name (required)
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootServiceHostComponents/component_name, RootServiceHostComponents/host_name, RootServiceHostComponents/service_name)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getRootServiceHostComponentsAsync(String serviceName, String hostName, String fields, final ApiCallback<List<RootServiceHostComponentResponseWrapper>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getRootServiceHostComponentsValidateBeforeCall(serviceName, hostName, fields, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<RootServiceHostComponentResponseWrapper>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getRootServices
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootService/service_name)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getRootServicesCall(String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/services";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (fields != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("fields", fields));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/plain"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getRootServicesValidateBeforeCall(String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        

        com.squareup.okhttp.Call call = getRootServicesCall(fields, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Returns the list of root-level services
     * 
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootService/service_name)
     * @return List&lt;RootServiceResponseWrapper&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<RootServiceResponseWrapper> getRootServices(String fields) throws ApiException {
        List<RootServiceResponseWrapper> resp = getRootServicesWithHttpInfo(fields);
        return resp;
    }

    /**
     * Returns the list of root-level services
     * 
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootService/service_name)
     * @return ApiResponse&lt;List&lt;RootServiceResponseWrapper&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<RootServiceResponseWrapper> getRootServicesWithHttpInfo(String fields) throws ApiException {
        com.squareup.okhttp.Call call = getRootServicesValidateBeforeCall(fields, null, null);
        Type localVarReturnType = new TypeToken<RootServiceResponseWrapperPack<RootServiceResponseWrapper>>(){}.getType();
        ApiResponse<RootServiceResponseWrapperPack<RootServiceResponseWrapper>>  execute = apiClient.execute(call, localVarReturnType);
        return execute.getData().getItems();
    }

    /**
     * Returns the list of root-level services (asynchronously)
     * 
     * @param fields Filter fields in the response (identifier fields are mandatory) (optional, default to RootService/service_name)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getRootServicesAsync(String fields, final ApiCallback<List<RootServiceResponseWrapper>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getRootServicesValidateBeforeCall(fields, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<RootServiceResponseWrapper>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
